src/miniscript/satisfy.rs
The satisfier now creates witness as the following safety rules.
1) If you can satisfy a weak branch, you must satisfy it. 2
2) Satisfy using only the minimum required branches. 
3) If there are more weak branches than required to satisfy, satisfy the cheapest ones.
This PR builds on the refactor PR
=> Adds safety logic for satisfier

fuzz/fuzz_targets/compile_descriptor.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs
- Added Ref-counting for decode::Terminal
- Changed compiler logic based on refcounting instead of cloning
=> Added Ref counting for Terminals 

src/miniscript/types/extra_props.rs, src/policy/compiler.rs, src/policy/concrete.rs
Added non-push op-code count for miniscript fragments
=> Op Code Count for Miniscript 

Cargo.toml, src/descriptor/mod.rs, src/descriptor/satisfied_constraints.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/semantic.rs
Looks like we are inconsistent with Pieter's and Ivy's implementation with Older and After. Changed
=> Older-after interchange bug

Cargo.toml, examples/htlc.rs
Based on the findings in #33, here is an example that creates an HTLC with miniscript.
=> Add example for creating an HTLC with miniscript

src/descriptor/create_descriptor.rs
Avoid panic when processing old school P2PK script (`OP_PUSHBYTES_33 <33 random bytes> OP_CHECKSIG`) using `from_txin_with_witness_stack`.
Fixes #51.
[`?w=1` diff (excludes whitespace changes)](https://github.com/apoelstra/rust-miniscript/pull/52/files?w=1)
=> Avoid panic when processing old school P2PK script (OP_PUSHBYTES_33 <33 random bytes> OP_CHECKSIG) using from_txin_with_witness_stack

src/policy/compiler.rs, src/policy/concrete.rs
Addresses #48 , #47 , #46 , #45 , #44 
Thanks @practicalswift for pointing these out
=> Added input sanitation to policy

Cargo.toml, fuzz/Cargo.toml, fuzz/fuzz_targets/roundtrip_miniscript_script.rs, fuzz/fuzz_targets/roundtrip_miniscript_str.rs, src/lib.rs
Also bumps the version to v0.12.0
=> Update rust-bitcoin depdency to v0.23.0

src/descriptor/mod.rs, src/miniscript/decode.rs, src/miniscript/mod.rs
=> Fix roundtrip_miniscript_script that fails on `006400675168`

src/policy/compiler.rs
Define a simple type alias to make the code shorter
=> compiler.rs: Define PolicyCache<Pk> type

src/miniscript/astelem.rs, src/miniscript/mod.rs
I think #81 is now completely resolved.
=> Fixed pk_k bug, added test

.vscode/settings.json, examples/parse.rs, src/descriptor/mod.rs
=> Miniscript Root Level Check for Descriptors

src/descriptor/mod.rs, src/lib.rs, src/macros.rs, src/miniscript/mod.rs, src/policy/concrete.rs, src/policy/semantic.rs
Also changed the existing serde impls to use the macro.
=> Add serde impls for policies using macro

src/descriptor/satisfied_constraints.rs
Still discovering remains of #37.
=> More csv ctlv fixes

src/psbt/mod.rs
micro-nit i just noticed while reading the implem.
=> [doc] psbt: bip is bip-0174

src/policy/compiler.rs
Cherry-picked and rebased version of #109
=> Switch Policy to use BTreeMap from HashMap

src/descriptor/mod.rs
=> Fix fuzzer failure

contrib/test.sh
=> Changed miri tests passing

src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/policy/concrete.rs, src/psbt/mod.rs
Fixes #122 . Thanks to Russell and simplicity implementation of timelocks for pointing out the details in BIP65/112.
=> Psbt bip fixes

src/descriptor/mod.rs, src/descriptor/satisfied_constraints.rs, src/expression.rs, src/lib.rs, src/miniscript/context.rs, src/miniscript/iter.rs, src/miniscript/lex.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/psbt/finalizer.rs, src/psbt/mod.rs
Added lints from rust-bitcoin.
changed [forbid(unsafe_code)] to [deny(unsafe_code)] as we are actually using unsafe code in ScriptContext
=> Added lints from rust-bitcoin

src/descriptor/mod.rs
Without this patch two different secp contexts are needed in order to interact with the library: one that has the `Verification` flag to use with `ToPublicKey` and one with `SignOnly` to call methods on extended keys.
By accepting a generic parameter one can just make an `All` instance and use it anywhere.
=> descriptor: Accept a generic Secp256k1 ctx instead of just `SignOnly`

Cargo.toml, examples/xpub_descriptors.rs, src/lib.rs
Add an example for using `DescriptorPublicKeyCtx`
=> Xpub example

src/descriptor/satisfied_constraints.rs
Added a panic for SortedMulti satisfied constraints
along with some explaination.
=> Sorted Multi explaination for satisfied constraint

src/descriptor/mod.rs
[This comment](https://github.com/rust-bitcoin/rust-miniscript/pull/180#pullrequestreview-530825697) mentioned the need for a test. Also tried to reduce the boilerplate a bit.
=> Test Display/Debug for SortedMultiVec

Cargo.toml, src/miniscript/satisfy.rs, src/psbt/finalizer.rs
More bug fixes from our integration tests. Looks like I messed up #157 again with `older/after` again. I think we should probably release a patch version with this fix.
=> Satisfy fixes

src/descriptor/mod.rs, src/psbt/finalizer.rs
Does the check for all SigHashTypes. Earlier this only checked if SigHash was explicitly set.
The second commit fixes #202
=> Minor cleanup for psbt finalizer

Cargo.toml, src/psbt/mod.rs
A sneaky bug i found while migrating my cooked satisfier to The Official Psbt Satisfier :tm:.
=> PSBT satisfier fix

Cargo.toml, src/policy/compiler.rs
I didn't add a test in https://github.com/rust-bitcoin/rust-miniscript/pull/149 and we had a regression :(
This should prevent it, and i still have some more bound checks to come..
Based on https://github.com/rust-bitcoin/rust-miniscript/pull/206
=> Test Segwit standard limitation

src/lib.rs, src/miniscript/satisfy.rs, src/psbt/mod.rs
Required for Integration tests in #162 .
=> Add psbt preimage satisfaction logic

fuzz/fuzz_targets/parse_descriptor.rs, src/miniscript/types/correctness.rs
And disables a fuzz test which will be after I fix upstream issue in rust-secp256k1
=> fix miniscript typesystem bug

src/descriptor/mod.rs, src/descriptor/pretaproot.rs, src/descriptor/tr.rs, src/lib.rs
Still not completely sure if this is what you wanted. I think we might also want new descriptor enums for `PreTaprootDescriptor` and `AddressableDescriptor`
=> Add pretaproot descriptor and addressabledescriptor

src/descriptor/mod.rs, src/descriptor/tr.rs, src/expression.rs, src/interpreter/mod.rs, src/policy/compiler.rs, src/policy/mod.rs, src/policy/semantic.rs
=> Misc: bug fixes 

src/lib.rs
When doing #327 this one got missed
=> Implement ToPublicKey for secp PublicKey

src/descriptor/tr.rs, src/miniscript/limits.rs
=> Use rust-bitcoin taproot max node count constant

Cargo.toml, tests/test_desc.rs
Addresses [feedback ](https://github.com/rust-bitcoin/rust-miniscript/pull/420#discussion_r883522759) #420 's review
=> Remove bitcoin rand feature from integration testing

contrib/test.sh
Similar to https://github.com/rust-bitcoin/rust-bitcoin/pull/1178
=> Pin serde to 1.0.142

src/descriptor/checksum.rs
=> replaced if else return with mapping

.github/workflows/rust.yml, contrib/test.sh
Do a bunch of cleanups to the CI script and GitHub Actions config file. None of these changes change the amount of test coverage but we do achieve some de-duplication of test runs. Otherwise, clean up only.
=> CI cleanup

src/psbt/mod.rs
Currently we have a function to construct the script code for a P2WPKH, this code is now upstream in `rust-bitcoin` so we can use it.
Fix: #364
=> Use p2wpkh_script_code from rust-bitcoin

src/descriptor/tr.rs
=> Update TapTree::iter docs

doc/compiler.md, src/policy/concrete.rs
=> Add some compiler documentation

src/lib.rs
This PR hexifies the Error implementation as requested in TODO. Let me know if this works and then I can remove the "TODO : Hexify this " Comment from there. 
Signed-off-by: Harshil Jani <harshiljani2002@gmail.com>
=> hexify for better error message

Cargo.toml, contrib/test.sh, src/descriptor/checksum.rs, src/descriptor/key.rs, src/descriptor/tr.rs, src/miniscript/iter.rs, src/miniscript/satisfy.rs, src/policy/concrete.rs, src/policy/mod.rs
Also check minimum dependency versions.
=> clippy fixes

src/psbt/finalizer.rs
The way it was written seemed very prone to forgetting fields if new ones would be added. Like this it just keeps the required fields and all the rest is set to `Default::default()`.
=> psbt: Rewrite input replacement to avoid forgetting fields

CHANGELOG.md, Cargo.toml, src/miniscript/decode.rs, src/miniscript/mod.rs
=> Fix panic while decoding large Miniscripts from Script

src/descriptor/key.rs
Sorry if there are lint issues, I can try fixing them later. I am directly editing from github web UI
=> Update error message when parsing DescriptorPublicKey

Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, src/descriptor/key.rs
Just the logic fix; the error refactoring doesn't apply.
=> backport #830 to rust-miniscript 12.x
