rust-bitcoin/rust-miniscript

Cargo.toml, src/lib.rs, src/miniscript/astelem.rs
From #6 
I think the witness for pubkey should be 73 bytes signature instead of pubkey_size(p) + 2. Or am I missing something?
Could not get #6 to reopen because I deleted the branch locally and remotely.
=> Fixed max satisfaction size calculation bug for PK case

Cargo.toml, src/descriptor/mod.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/policy/compiler.rs
Changed node names `time` -> `time_e`, `time_t` -> `time`, `hash_t` -> `hash`. 
There adds a convention that the T version is always keyword and everything else (if distinct) is keyword_X.
=> Changed node names time -> time_e, time_t -> time, hash_t -> hash

fuzz/Cargo.toml, src/descriptor/create_descriptor.rs, src/descriptor/mod.rs, src/descriptor/satisfied_contraints.rs, src/lib.rs, src/miniscript/mod.rs
Added interpreter for miniscript and support for creating descriptors from transaction objects. Addresses the comments in #9 . 
This would again be needed to be rebased after structure changes in AstElem.
=> Added interpreter for miniscript and descriptor creation logic

Cargo.toml, src/descriptor/create_descriptor.rs, src/descriptor/mod.rs, src/descriptor/satisfied_contraints.rs, src/lib.rs, src/macros.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs
-Change miniscript to save type information
-Change tests to use string inputs instead of `decode::Terminal`(previsouly `asterm::AstElem`)
=> Refactor for miniscript to save type information

fuzz/fuzz_targets/compile_descriptor.rs, fuzz/fuzz_targets/roundtrip_concrete.rs, fuzz/fuzz_targets/roundtrip_descriptor.rs, fuzz/fuzz_targets/roundtrip_miniscript_str.rs, fuzz/fuzz_targets/roundtrip_policy.rs, fuzz/fuzz_targets/roundtrip_semantic.rs, src/descriptor/create_descriptor.rs, src/descriptor/mod.rs, src/descriptor/satisfied_contraints.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs, src/psbt/mod.rs
Ther are two commits in total
- Add PubkeyTrait:
- Changed Semantic Policy to only accept Pkh for the below reasons. 
This allows to following invariant.
`Lift(Concrete) == Concrete -> Miniscript -> Script -> Miniscript -> Semantic`
Lifting concrete policy is equivalent to the following:
Compiling Concrete to Miniscript followed by
Encoding the miniscript to Script
Decoding it back to Miniscript
And finally lifting it back to Semantic
=>  Added PubkeyTrait and changed Miniscript/Terminals to a single generic

.travis.yml, contrib/test.sh, src/descriptor/create_descriptor.rs, src/descriptor/mod.rs, src/descriptor/satisfied_contraints.rs, src/expression.rs, src/lib.rs, src/macros.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/lex.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/correctness.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/malleability.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs, src/psbt/mod.rs
2 commits:
- output of `cargo fmt`
- Adds cargo fmt check to travis. 
There were different commands for formatting check for 1.22.0 and other versions. I just added it for stable version.
=> Add cargo fmt

src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs
Users should not provide `Pkh` input to the policy file.
=> Removed Pkh Type from concrete policies

src/miniscript/mod.rs
- Added custom Eq/PartialEq for miniscript
- Removed Ord/PartialOrd derive rules for types.
=> Removed Ord/PartialOrd derive rules for types.

src/descriptor/satisfied_constraints.rs, src/lib.rs, src/miniscript/astelem.rs
Changed the naming to be consistent with bitcoin.sipa.be/miniscript
=> Included wrappers for `l`,`u`,`t`.

contrib/test.sh, examples/sign_multisig.rs
Also added each current example to Travis to avoid unnecessary regressions.
`max_satisfaction_weight` needs real tests, but this can be done later.
=> Example weight estimation for multisig

src/policy/compiler.rs
`best_e` and `best_w` were almost identical.
=> Compiler code deduplication

README.md
I was wondering why this crate isn't using the 2018 edition yet.
More details can be found in the discussion for #34:
* https://github.com/apoelstra/rust-miniscript/pull/34#issuecomment-524173776
* https://github.com/apoelstra/rust-miniscript/pull/34#issuecomment-524419649
Or in https://github.com/rust-bitcoin/rust-bitcoin/issues/338
=> Add clarification on 2015 edition usage

src/miniscript/mod.rs
From https://en.wikipedia.org/wiki/RAS_syndrome
> RAS syndrome (where "RAS" stands for "redundant acronym syndrome",
making the phrase "RAS syndrome" self-referential) is the use of one
or more of the words that make up an acronym (or other initialism) in
conjunction with the abbreviated form.
=> Cure RAS Syndrome

fuzz/fuzz_targets/roundtrip_descriptor.rs, fuzz/fuzz_targets/roundtrip_policy.rs, src/descriptor/mod.rs, src/expression.rs, src/miniscript/astelem.rs, src/policy/semantic.rs
* fix `thresh` and `multi` descriptors with no arguments
* fix roundtrip_concrete roundtrip for "older(03)"
* fix roundtrip_descriptor for "c:pk_k" ("pk" alias)
=> Fix fuzz crashes (fixes #89)

fuzz/fuzz_targets/roundtrip_descriptor.rs, fuzz/fuzz_targets/roundtrip_miniscript_str.rs, src/descriptor/mod.rs
The last of fuzz fixes. We had to rely on regex for checking roundtrips for miniscript and descriptors after changes from #81
=> Final fuzz fixes

src/descriptor/mod.rs, src/miniscript/satisfy.rs
Given an `and` instruction, miniscript produces a witness stack that
is wrongly ordered:
The left branch of an `and` instruction is evaluated first, which means
whatever witness stack is produced by this branch needs to come _after_
the witness stack of the right branch.
Unfortunately, Witness::combine simply concatenates the two vectors,
resulting in the witness stack for the left branch to end up _before_ the
one for the right branch.
This is what we currently have:
```
Witness in memory:
|----A-----|----B-----|--and(A,B)--|
Witness stack evaluation:
Round 0:
Stack:          Instructions:
check(A) check(B)
|----B-----|
|----A-----|
Round 1:
Stack:          Instructions:
|----B-----| check(A) check(B)
|----A-----|
Round 2:
Failure due to wrong signature.
```
With this patch, this changes …
=> Miniscript produces witness stacks with wrong order of signatures for `and` instructions

src/lib.rs, src/miniscript/lex.rs, src/miniscript/mod.rs
This PR has two commits:
1. Decoding bug fix for 65-byte pubkey
2. Changing valid script size form 10k to 100kb as point out correctly in https://github.com/apoelstra/rust-miniscript/pull/101#discussion_r446829741
=> Decode 65 bytes pubkey

.travis.yml, contrib/test.sh, examples/verify_tx.rs, fuzz/fuzz_targets/compile_descriptor.rs, fuzz/fuzz_targets/roundtrip_concrete.rs, fuzz/fuzz_targets/roundtrip_descriptor.rs, fuzz/fuzz_targets/roundtrip_miniscript_script.rs, fuzz/fuzz_targets/roundtrip_miniscript_str.rs, fuzz/fuzz_targets/roundtrip_semantic.rs, src/descriptor/create_descriptor.rs, src/descriptor/mod.rs, src/descriptor/satisfied_constraints.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/psbt/mod.rs
Adds context to Miniscript. I have made a bunch of design decisions here with minor changes in API for satisfied constraints. 
I could not find a clean way to enforce constraints for the only bitcoin::PublicKey type because our code was generic, so had to hack in `IS_BITCOIN_PUBKEY` to the Miniscript Trait. 
This builds on top of #95 , would rebase and squash as needed.
=> Add ScriptContext to Miniscript

src/miniscript/decode.rs, src/miniscript/mod.rs
Copy of #78 with the unit test fixed
=> Issue from pull/63

CHANGELOG.md, Cargo.toml, README.md
Release 1.0.0
Added Changelog, Readme. 
- ba02e75 Fix parser for issue #63
- 4df9d76 Removed Legacy enum from types
- cac1a26 Added Miri tests on travis
- c93bdef Added ScriptContext to Miniscript
- bcbe365 decode 65 bytes pubkeys too
- 0576765 Change limit to 100kb
- 824fed2 Flip argument order of Witness::combine for and_v and and_b
- 6438f10 Improve Miniscript robustness
- f556fd6 Case Sensitve Fuzz fixes
- 475f6a5 PkH aliases
- 1d6f4e9 Upstream fixup, .gitignore
- f2c98a3 Final fuzz fixes
- 4374578 Miniscript Root Level Check for Descriptors
- b0c6452 Policy fixes
- ff9373a And or fragments must have exactly two arguments
- 71a52f0 fmt fixes
- e40e012 removed redundant roundtrip_policy
- 63c895c suppressed and fixed warnings
- 835a7a7 fixed benches
- 7fe3466 Added unit tests from fuzz …
=> Release 1.0.0

src/policy/concrete.rs, src/policy/semantic.rs
A small typo I noticed on docs.rs
=> policy: Corrected an inverted documentation for `Older` and `After`

src/miniscript/decode.rs
Double checked, this time I hope there is no more occurrence! :)
fixes #111
=> miniscript: doc: fix Older/After interchange in doccomments

src/descriptor/mod.rs
To generate valid Segwit sighashes, the `witness_script()` could be used
for P2WSH outputs's `scriptCode`. However a P2PKH Script would have to be
reconstructed by-hand for P2WPKH.
This unifies the way to get the `scriptCode` for any Segwit output
defined using a rust-miniscript descriptor.
Note that we don't bother checking for CODESEPARATOR as we don't produce
Scripts containing such opcode.
I did not add a test yet, but wanted your input on how to test this: could some tests be modified to use real signatures and can i introduce libbitcoinconsensus as a dev-dependency in order to check the scripts against it ? This would indirectly check that the `scriptCode` is correct.
=> descriptor: add a method to get the `scriptCode` as per bip-0143

examples/htlc.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs
Implemented policy entailment algorithm. It is also possible to optimize this even further by memorizing results in hashmap, but this works fast for desired use cases. 
The first commit fixes some bugs in normalization code and also changes the logic so that we convert everything to `thresh`. As discussed, we do not require `and` and `or` in semantic analysis. Note that the `FromStr` and `Debug`, `Display` are updated to the to print `and` and `or` while are internally represented as `thresh`.
This will be helpful in #113 where it is possible to switch between `And` and `thresh` in order to maintain the current invariant that  
`policy -> compile -> lift == policy -> lift`.
=> Policy entailment

src/policy/compiler.rs
This adds a special case to the compilation of the `thresh(k, subs)` policy to
miniscript: when all sub-policies are keys and k == subs.len() this
compiles to a combination of and()s instead of a thresh().
The first commit adds some tests for the policy->miniscript compilation of different combinations of `k` and pubkeys under the `thresh()` policy.
The second commit special cases `k == pubkeys.len()` (when `> 20`) to eventually produce slightly more efficient Bitcoin Script:
```
<pubkey1> CHECKSIGVERIFY <pubkey2> CHECKSIGVERIFY  <pubkey3> CHECKSIGVERIFY ... <pubkeyN> CHECKSIG
```
Instead of
```
<pubkey1> CHECKSIG SWAP <pubkey2> CHECKSIG ADD SWAP  <pubkey3> CHECKSIG ADD SWAP ... <pubkeyN> CHECKSIG ADD N EQUAL
```
As mentioned by sipa on IRC we can also special-case `k==1` to a combination …
=> Optimize policy compilation for N-of-N tresholds

src/lib.rs
Super trivial first time PR to `rust-miniscript` :) 
Fix whitspace issue in function rustdoc, add missing whitespace character.
=> Add missing whitespace to rustdoc

src/descriptor/create_descriptor.rs
Fixes https://github.com/rust-bitcoin/rust-miniscript/pull/130#discussion_r491177807
=> Simplification of instruction iterators use by descriptors

src/psbt/mod.rs
The satisfier was only implemented for `bitcoin::PublicKey` and could not be reimplemented for a more generalistic key downstream.
Also, it makes sense after #131 (i have a rebased version for my own needs here https://github.com/darosior/rust-miniscript/commits/satisfy_xpubs). All signatures are looked for by raw public key, and thus should be added to the mapping with `to_public_key()` (which derives the one pointed by the `DescriptorPublicKey` in #131).
Could have rebased it on #131 to add a test xpub-descriptor, but seemed overkill as the change is pretty straightforward.
=> psbt: satisfy any ToPublicKey key

src/miniscript/iter.rs, src/miniscript/mod.rs
I'll start with this sample one for concept (n)ACK and than will work on other types (like public keys)
=> Miniscript iterators

src/descriptor/mod.rs
This fixes my confusion in #123 that @apoelstra pointed out.
=> descriptors: define script_code() for legacy outputs

src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs
It makes sense to have a corresponding type for trivial/unsatisfiable in the concrete compiler as it's quite useful when generating Policy from a higher level. This patch attempts to add these types.
See IRC:
```
[9/30/20 18:00] <jeremyrubin> Would anyone be opposed to adding a Unsatisifiable and Satisfied type to Policy. Context: sometimes when writing generic code to generate conditions, a component want to return "no further condition required" or "we don't want to authorize ever on this path". This is, of course, emulable with a higher order wrapper around the Policy type, but it seems simpler to add the types into Policy itself. There would be some identities, e.g.
[9/30/20 18:00] <jeremyrubin> , Or([A, Unsat]) = A, Or([A, Sat]) = Sat, And([A, Unsat]) = Unsat, And([A, Sat]) = A …
```
=> Add Trivial and Unsatisfiable types to Concrete Policy

fuzz/Cargo.toml, fuzz/fuzz_targets/parse_descriptor.rs, src/descriptor/mod.rs
This is a rebased, cleaned up and amended version of #93.
It's based on #130.
<details>
<summary>Here is the diff with a [rebased-on-master #93 ](https://github.com/darosior/rust-miniscript/commits/sgeisler_2020-06-descriptor-key_rebased) at commit cdfab02acfe13aeb3c2743b95208f255da4856a0</summary>
<p>
```patch
diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
index dac83c0..3d34f23 100644
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -58,8 +58,8 @@ jobs:
- 1.22.0
- beta
- stable
-    steps:      
-      - name: Checkout Crate 
+    steps:
+      - name: Checkout Crate
uses: actions/checkout@v2
- name: Checkout Toolchain
uses: actions-rs/toolchain@v1
@@ -67,6 +67,8 @@ jobs:
profile: minimal
toolchain: ${{ matrix.rust }}
override: true
+      - …
```
=> DescriptorPublicKey, second pass

src/psbt/finalizer.rs, src/psbt/mod.rs
Changes the psbt satisfaction API.
=> Psbt satisfy

CHANGELOG.md, Cargo.toml
Includes the following commits:
03b94d9 Switch Policy to use BTreeMap instead of HashMap
67ea9e1 Update Psbt satisfier to for timelocks
31810ae Added psbt satisfy for after/older
78a56be Added PsbtInputSatisfier
eae1634 Merge pull request #119 from sanket1729/psbt_fixes
c2b1fa7 Added psbt example
099d68a Implemnented finalizer
a71025f Added pkh lookup for psbt
5c16f2f Rework error types. Complete extractor
0fb11c0 Added from impl interpreter error
8e7410b Decouple satisfaction API
70f5490 Helper for conversion of bitcoinsig from rawsig
e0fc688 Merge pull request #131 from darosior/descriptor_publickey
28158a3 fuzz: add a fuzz target for descriptor parsing
5ac4112 descriptor: allow "raw" pubkeys to have origin
367eda0 Make Descriptors derivable
021880e Implement ToPublicKey for …
=> Release 2.0.0

src/descriptor/mod.rs, src/lib.rs
Just noticed i didn't implement Error for the descriptor pubkey parsing error (happens to be problematic downstream)...
Also re-exported `DescriptorPublicKey` which [was suggested previously](https://github.com/rust-bitcoin/rust-miniscript/pull/131#issuecomment-699036746) but i overlooked
=> Descriptor pubkeys fixups

examples/sign_multisig.rs, src/descriptor/mod.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/miniscript/types/extra_props.rs, src/policy/compiler.rs
This is the first part of #148, in order to fix #132.
This comports:
- a few drive-by cleanup commits added as i was reading the cost computation internals
- an API break: change max_witness_elements() to return an Option instead of unwrap()ing internally
- an addition of bounds-check for segwit standardness rules under the Segwitv0 context
- a move of the OPs count check to context in order to also check it at parse time (not only compilation) 
The second part is -coming soon :tm: and- storing  the cost in witness elements in the ExtraData struct in order to avoid the suboptimal recursion at each check.
=> Check for segwit standardness limits

Cargo.toml
This adds pass-through flags for enabling rand on rust-bitcoin and enabling serde on rust-bitcoin.
=> Add Cargo.toml Flags

src/descriptor/mod.rs, src/descriptor/satisfied_constraints.rs, src/lib.rs, src/miniscript/context.rs, src/miniscript/satisfy.rs, src/policy/mod.rs
=> Add "sortedmulti" descriptor support

fuzz/Cargo.toml, fuzz/fuzz_targets/parse_descriptor_secret.rs, src/descriptor/mod.rs
I'm opening this right PR now mostly to gather feedback, since many things are still missing and need a lot of polishing.
This PR builds on top of #93 ([here](https://github.com/sgeisler/rust-miniscript/compare/2020-06-descriptor-key...afilini:sgeisler-descriptor-key)'s the diff with it), so it incorporates the `DescriptorKey` concept from @sgeisler and extends it to also support parsing of secrets (WIF or xprv) in Descriptors.
It implements pretty much what @apoelstra described in #93, which is having a way to parse a descriptor with secrets, but immediately separate them out and store them in a map, and only have public types in the descriptor. This is achieved with the `SplitSecret` trait that can be implemented on types that are `MiniscriptKey` that may contain secrets, and it adds a …
=> Add `DescriptorSecretKey` and `Descriptor::parse_secret()`

examples/htlc.rs, examples/parse.rs, examples/sign_multisig.rs, examples/verify_tx.rs, fuzz/fuzz_targets/roundtrip_miniscript_script.rs, src/descriptor/create_descriptor.rs, src/descriptor/mod.rs, src/descriptor/satisfied_constraints.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/iter.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/policy/compiler.rs, src/psbt/finalizer.rs, src/psbt/mod.rs
Although the diff is large, most of it just compiler guiding me on how to fix the errors. As can be seen from the diff the change is pretty invasive.  
On the other hand, we can have the user use the translate functions to get a `Miniscript<bitcoin::PublicKey, _>` and then use the API operations on those. Considering the API changes required here, I am leaning toward the other option of not implementing `ToPublicKey` to DescriptorKey at all. Even for tweaked keys where we need cryptographic operations, we should use the translate functions. 
I am starting to think that having additional parameters for address, max_satisfaction_wieght, etc might not be worth it. 
Does not currently build/test for compiler feature. I can fix that depending on what we decide. 
w.r.t #163, I think the best …
=> Update ToPublicKey API to take in context param

src/descriptor/mod.rs
The keys part was encoded with quotes around it due to the use of `{:?}`,
like so: `wsh(sortedmulti(1,"xpub66..,xpub69.."))`.
While at it, I also took the liberty to avoid unnecessary allocations (similarly to how `Display` is implemented for `Terminal::Multi`) and to DRY things by delegating `Debug` to `Display`.
=> Fix Display/Debug For SortedMultiVec

src/descriptor/mod.rs
Considering that the fields of the struct are already public keeping it private
doesn't really prevent anybody from creating an instance with some weird arguments.
Even worse, it forces the user to manually instantiate the struct, bypassing all
the necessary checks present in the constructor.
=> descriptor: Make `SortedMultiVec::new()` public

src/descriptor/mod.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs
Based on the comment: 
https://github.com/rust-bitcoin/rust-miniscript/pull/161#discussion_r517353815
> The attacker only has access to hash preimages that honest users have access to as well. This is a reasonable assumption because hash preimages are revealed once globally, and then available to everyone. On the other hand, making the assumption that attackers may have access to more preimages than honest users makes a large portion of scripts impossible to satisfy in a non-malleable way.
from bitcoin.sipa.be/miniscript
=> Add malleable signer

src/descriptor/mod.rs, src/lib.rs, src/miniscript/context.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/policy/compiler.rs, src/util.rs
Satisfy can fail if the resource limits are exceeded
=> Fail satisfy when resource limits exceed

doc/resource_limitations.md, src/miniscript/context.rs, src/miniscript/limits.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/policy/concrete.rs, src/psbt/mod.rs
We returned a ScriptSig-related error for the Witness.
Also added a commit to move the constraints to their own module since their number grew up significantly :)
=> Satisfy error: return a max witness size error for Segwitv0

src/descriptor/mod.rs, src/interpreter/error.rs, src/lib.rs, src/miniscript/analyzable.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/psbt/mod.rs
Lifting should fail for miniscripts/descriptors
- timelock combination
- branch exceeds resource limits
Lifting fails for concrete policies:
- timelock combination
- If there is a branch that can exceed resource limits, our compiler would not create miniscripts anyway. And it general, it is difficult to check the resource limit checks without compiling.
=> lift failure bug fixes

src/miniscript/context.rs, src/miniscript/types/extra_props.rs
Thanks to @darosior for pointing out this bug. In our context checks, I implemented a short circuit branch to error out when the resource limit exceeded. But when the check function(e.g max_satisfaction_witness_elements) itself returned `None`, we had a bug which returned Ok(()). 
I think it is worth changing the API's that return None to return a result so that they are more descriptive and b) these types of bugs don't occur. ( '?' is easy to write and review. Someone I missed to match `None`).
=> Return Err on None in context checks

src/descriptor/mod.rs, src/lib.rs
We could previously create `sortedmulti()` invalid by consensus.
Stole 79a0e62 from #197 .
=> Standard sortedmulti

examples/sign_multisig.rs, fuzz/fuzz_targets/roundtrip_miniscript_script.rs, src/descriptor/mod.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/mod.rs, src/policy/compiler.rs
To improve ergonomics and efficiency. You don't need to do an ecmult to figure out the length of your public key! Also should be possible on string descriptors now I guess?
=> Remove ToPkCtx from length/satisfaction_weight

src/interpreter/stack.rs
This trivial change actually prevents us from running into a mystifying error [here](https://github.com/comit-network/droplet/pull/29/checks?check_run_id=1557115096#step:7:252) when building to wasm.
=> Replace empty array equality comparison with is_empty()

src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/lib.rs, src/miniscript/context.rs, src/miniscript/mod.rs
~Build on top of 216. Will rebase after #216 is merged.~
Ready for review
=> Change options to result in all APIs

src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/lib.rs, src/macros.rs, src/miniscript/astelem.rs, src/miniscript/mod.rs, src/policy/concrete.rs, src/policy/semantic.rs
Without this bound you can't deserialize, but there are lots of in-memory things you might like to do with weird keytypes (e.g. looking up a bunch of aux data from a database and tagging keys with them, or even attaching an `&'a wallet`) where the requirement to impl `FromStr` is extremely onerous.
=> remove FromStr bound on MiniscriptKey and MiniscriptKey::Hash

src/miniscript/context.rs
Without this you can't do a `Hash` derive on types containing `Miniscript<Ctx, _>` fields
=> Hash derive for miniscript context types

src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs
Only include it for the outer descriptor and not for the inner one.
This was already considered for `sh(wsh(..))`, but not for `sh(wpkh(..))`, which resulted in `sh(wpkh(<key>)#<checksum1>)#<checksum2>`.
=> Fix checksum for nested sh(wpkh())

Cargo.toml, src/miniscript/satisfy.rs
The first one is a serious one which caused incorrect results. 
~~While the second one is a relaxation of rules that allow dissatisfactions to be malleable. Because of this, earlier we were not able to satisfy a miniscript that required ORI dissatisfaction where both of the available dissatisfactions were malleable. (which is almost always the case).~~
=> Satisfaction bugs

src/policy/concrete.rs, src/policy/semantic.rs
These previously untested methods result in a compiler error if you ever tried to call them. This happens because if you put &mut in front of the type when you recursively pass it to another call you are actually creating a &mut &mut since the argument may already be a &mut. This ends up in infinite &muts prefix. The compiler only figures this out when you call the method (not at compile time of the library).
I fixed this by having an inner function take a &mut FnMut as the argument and so breaking the chain of &mut. The public functions remains the same. There might be a better way to fix this but I tried for more than an hour to do this without an inner and outer function and nothing else worked.
=> Workaround rust compiler goof in Policy::translate_pk

src/descriptor/mod.rs
Without this, I cannot wrap ConversionError thrown from derive_public_key in a downstream library.
=> export ConversionError

.github/workflows/rust.yml, README.md, contrib/test.sh, src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/miniscript/context.rs
Actually, I'm quite confused by this. The `Miniscript` type derives `Hash` without the `ScriptContext` trait requiring `Hash`, but when I tried for `Descriptor` it would complain about that. Is there some magic that made it work in `Miniscript`? Ideally we wouldn't require the `Hash` on `ScriptContext` there, but it doesn't hurt either.
=> Derive std::hash::Hash for Descriptor et al

src/miniscript/mod.rs
A small nit i noticed while reviewing #236 :)
=> miniscript: remove a redundant check for non-ASCII chars

src/interpreter/error.rs, src/interpreter/mod.rs, src/miniscript/satisfy.rs, src/psbt/finalizer.rs
I forgot to append the ANYONECANPAY flag with my boutique signer for hand-testing and spent some time before realising we were actually treating the last byte of the sig as a valid SIGHASH_ALL in the finalizer !
I believe it's cleaner to error early on too short signatures.
EDIT (made after the comments below): actually if i was just using SIGHASH_ALL i could have messed up my sighash type and not notifying it. Even though checking this is on the user of the lib, i believe it would be much nicer to not silently accept invalid-by-standardness signatures in rust-miniscript.
=> Explicitly error on non-standard sighash types

src/miniscript/decode.rs, src/miniscript/mod.rs
Parsing an `EQUALVERIFY` ending thresh fragment failed roundtrip.
=> Thresh bug with equal verify

Cargo.toml
Needed because some method from .2 is used now.
=> Bump bitcoin dependency to 0.26.2

Cargo.toml
Needed because `rust-bitcoin v0.27` has added Bech32m address support, see the complete changelog [here](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/CHANGELOG.md#027---2020-07-21).
=> Bump rust-bitcoin dependency to v0.27

src/policy/semantic.rs
Related to #247  and #248 . Added the `at_height` function for analyzing policies and `absolute_timelocks` for semantic analysis.
=> Added `at_height` and `absolute_timelocks`

src/miniscript/mod.rs, src/policy/compiler.rs, src/policy/semantic.rs
minimum_n_keys returns None if the policy is not satisfiable.
It would previously (erroneously) return 0.
Fixes #264
=> policy: minimum_n_keys returns an Option

src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs
Wonder if we should check that the timelock value is minimal too, what do you think?
=> miniscript/types: check that timelock values aren't too large

src/miniscript/context.rs, src/miniscript/mod.rs
The previous genericization of the ScriptContext methods permitted some very surprising behaviors that are certainly not intended. The Ctx Parameters should in all cases be a Self parameter as far as I can tell. This PR fixes this issue.
fixes https://github.com/rust-bitcoin/rust-miniscript/pull/255#discussion_r711772814
Technically, this is a breaking change as the generic paremeter count decreases and it is not generally inferred I think.  It's easy to fix, and any code which could not be fixed trivially would be hopelessly broken/buggy.
=> Fix over-generic parameterization of ScriptContext

src/descriptor/key.rs
It's clearer to return `0x00000000` if we don't know the origin. This is arguably not an API break since, well, this code path could not be taken without panic'ing before.
=> descriptor/key: fix master fingerprint when there are none

src/descriptor/sortedmulti.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/miniscript/limits.rs, src/policy/compiler.rs
We check at parsing time, but we would still allow to create a `Multi` with `> 20` keys and not error on sanity checks! I'd add a test but wanted to push a patch quickly first.
Reported by @danielabrozzoni .
=> Context: check for the maximum number of public keys in a `CHECKMULTISIG`

integration_test/run.sh
Closes https://github.com/rust-bitcoin/rust-miniscript/issues/287
=> use a single-use temp name for integration test dir

Cargo.toml, examples/sign_multisig.rs, examples/verify_tx.rs, examples/xpub_descriptors.rs, integration_test/Cargo.toml, integration_test/src/main.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/descriptor/sh.rs, src/interpreter/error.rs, src/interpreter/inner.rs, src/interpreter/mod.rs, src/lib.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/policy/compiler.rs, src/psbt/finalizer.rs, src/psbt/mod.rs
Update to a version of dev rust-bitcoin so that we can prepare for rust-miniscript release. The integration tests are updated to point a personal fork of rust-bitcoincore-rpc to have rust semver type issues. 
After we have this, we can make progress on tapscript while we await finalized rust-bitcoin release. After which, we can remove the git dependencies and have crates.io dependencies instead.
=> Update to a dev version latest bitcoin master 0e2e55971275da64ceb62e8991a0a5fa962cb8b1

examples/sign_multisig.rs, examples/verify_tx.rs, fuzz/fuzz_targets/roundtrip_miniscript_script.rs, fuzz/fuzz_targets/roundtrip_miniscript_str.rs, src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/interpreter/error.rs, src/interpreter/inner.rs, src/interpreter/mod.rs, src/interpreter/stack.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/miniscript/iter.rs, src/miniscript/lex.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/mod.rs, src/psbt/mod.rs, src/util.rs
Adds support for MultiA script fragment. Builds on top of #255 .
Do not merge this until we have a rust-bitcoin release
=> Miniscript tapscript support (Pr 2 of 3)

README.md
Previously, just version-pinning the dependencies were unable to generate the lockfile properly. Manually generating lockfile before the same works!
=> Add Cargo-lockfile generation in README

examples/xpub_descriptors.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/lib.rs, src/miniscript/context.rs
=> Add support for x-only keys in descriptor

examples/xpub_descriptors.rs, src/descriptor/mod.rs
Resolves #302.  
- Updates the order of parameters in `derived_descriptor` function signature.
- Updates the P2WSH-P2SH and ranged xpub examples to call `derived_descriptor` function.
=> Update derived_descriptor signature and related examples

src/descriptor/mod.rs, src/descriptor/sh.rs
Useful if you already have an `W{s,pk}h` descriptor and wish to wrap it with P2SH.
This used to be [possible](https://github.com/shesek/minsc/blob/33433462e84e3903a70a9aac6f47e591df094127/src/stdlib/miniscript.rs#L149-L153) before the new inner types for the Descriptor enum variants, which has private fields that cannot be initialized externally.
=> Allow constructing Sh descriptors wrapping an existing Wsh/Wpkh

Cargo.toml, examples/verify_tx.rs, integration_test/Cargo.toml, integration_test/src/main.rs, integration_test/src/read_file.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/descriptor/sortedmulti.rs, src/interpreter/error.rs, src/interpreter/inner.rs, src/interpreter/mod.rs, src/interpreter/stack.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/context.rs, src/miniscript/iter.rs, src/miniscript/mod.rs, src/policy/compiler.rs, src/policy/mod.rs, src/psbt/finalizer.rs, src/psbt/mod.rs
Add taproot interpreter support. This is the second to last PR for taproot miniscript support. The last PR will add some more high-level APIs for taproot psbt and integration tests.
=> Taproot interpreter support

src/descriptor/tr.rs
This is needed for wallet libraries downstream to access for instance merkle root of the script.
=> Make Tr::spend_info public

src/psbt/finalizer.rs
We should check the witness script hashes to the redeem script in the
nested sh wsh case. Not the script pubkey
Caught up integration tests
=> Fix finalizer check for sh(wpkh)

src/interpreter/mod.rs
Support for multi_a interpreter. Required for interpreter check finalizer.
=> MultiA interpreter

src/psbt/finalizer.rs, src/psbt/mod.rs
- Cleanly separate the mutating part of the code such that if the psbt input finalization errors, that input is not mutated.
- Update API docs
=> Cleanups on Psbt APIs

src/descriptor/tr.rs
You can re-order commits to see that this is fixed.
=> Fix tr for each key bug

src/lib.rs
=> Implement MiniscriptKey for secp256k1 PublicKey

Cargo.toml, examples/verify_tx.rs, integration_test/src/test_cpp.rs, integration_test/src/test_desc.rs, src/interpreter/inner.rs, src/interpreter/mod.rs, src/miniscript/mod.rs, src/psbt/finalizer.rs, src/psbt/mod.rs
This is a draft API adopting new version of rust-bitcoin 0.28.0-rc.2
=> Bitcoin 0.28.0-rc.2

src/descriptor/key.rs, src/descriptor/mod.rs
Reported by: @afilini . 
This was a copy-paste error on my side :(
=> Enforce that x-only keys cannot be used in non-tr descriptors

CHANGELOG.md, Cargo.toml, examples/sign_multisig.rs, examples/verify_tx.rs, integration_test/src/test_cpp.rs, integration_test/src/test_desc.rs, src/descriptor/mod.rs, src/descriptor/tr.rs, src/interpreter/error.rs, src/interpreter/mod.rs, src/miniscript/mod.rs, src/policy/compiler.rs, src/psbt/mod.rs
Rename SigHash* into Sighash accross the repo
Reproducible with automatic case-sensetive search/replace
Make taproot leaf script depth to be u8 everywhere
I have changed the release notes title from 7.0.0-rc.2 to 7.0.0.
=> Release 7.0.0

integration_test/Cargo.toml
While we await rust-bitcoincore-rpc release, let's have this to make
sure that integrationt tests run and we get a nice green checkmark.
I really don't like seeing a red cross on all PRs :)
=> Hacky Fix for int CI failure

src/descriptor/sortedmulti.rs
We have what appears to be an error return but do not actually return
the error. This line needs an explicit `return` statement otherwise it
is a noop.
=> Actually return the error

src/lib.rs
In an effort to make the code more readable refactor the 4 `TranslatePk[X]` types by doing:
- Improve docs
- Shorten parameter names to assist formatting with no loss of clarity
- Use `where` instead of inline trait bounds
=> Refactor the TranslatePk types

src/lib.rs
Improve the code around trait `MiniscriptKey` by doing
- Improve docs
- Add regression tests
- Refactor the trait
=> Clean up trait `MiniscriptKey`

src/miniscript/types/extra_props.rs
Cost incurred for a single Schnorr signature in the witness stack := `<var_int><64-byte signature><sig_type>` = 1 + 64 + 1 (as clarified by @sanket1729 in #340 ).
=> Rectify `from_multi_a` max satisfaction size

Cargo.toml
Do trivial clean up to the manifest file. 
Warning: Totally non-urgent, possibly annoyingly trivial.
=> Clean up the manifest

integration_test/src/test_desc.rs, src/descriptor/mod.rs, src/psbt/mod.rs
Fixes #335 
This populates all relevant fields in a PSBT input according to a descriptor. Includes previously not yet implemented logic for populating `bip32_derivation` and `tap_key_origins`. Also optionally checks the `witness_utxo` and `non_witness_utxo`.
I renamed `PsbtExt::update_desc` to `PsbtExt::update_inp_with_descriptor` which calls `update_with_descriptor`
internally but retrieves the vout for the input for the `non_witness_utxo` check automatically. I removed the derivation range functionality because it didn't feel useful (and if it is then it probably belongs in a separate function). Let me know if you want me to add it back where it was or to provide an additional utility function to find which index a script pubkey was derived from.
=> Add PsbtInputExt::update_with_descriptor

integration_test/src/test_util.rs, src/descriptor/key.rs, src/descriptor/mod.rs
In an effort to better understand the `descriptor` module and its associated types; do some refactoring and re-naming of types making the key struct identifiers more terse.
- Patch 1: refactor, code layout
- Patch 2: docs improvements
- Patch 3: Minor refactor
- Patch 4: Use more terse names, this is the bulk of the PR
If this is too invasive for someone only recently making their way around the crate, feel free to say so :)
=> Increase terseness in descriptor module

src/lib.rs, src/miniscript/analyzable.rs
This helps a lot downstream, and we can do that now that rust-bitcoin derives `PartialEq` everywhere.
=> lib: implement PartialEq for miniscript::Error

src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs
Recently [0] we added a check on a value masked against `SEQUENCE_LOCKTIME_DISABLE_FLAG`, this check uses `x == 1` but x can never be zero since `SEQUENCE_LOCKTIME_DISABLE_FLAG` is equal to `0x80000000`.
Looking at the original commit it looks like we are trying to check for a value _higher_ than the flag value, so we can mask then use `x != 0` to see if the flag bit is enabled.
Found by clippy:
error: incompatible bit mask: `_ & 2147483648` can never be equal to `1`
CC: @darosior, have I understood this correctly man?
[0] commit: `commit a3dd9fe840c8cdae84e9d586cd9a9d6c195f0092`
=> Use != 0 instead of == 1 for check of masked value

integration_test/run.sh
Currently we have two initial output lines when running the integration test script. The first is confusing (to me at least) and the second is unnecessary it seems (please correct me if I am wrong).
- Patch one removes the warning: `bitcoind: no process found`
- Patch two removes the printing of `$PATH`
=> Make the integration script more quiet

src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/descriptor/tr.rs, src/miniscript/analyzable.rs, src/miniscript/astelem.rs, src/miniscript/mod.rs, src/policy/concrete.rs, src/policy/semantic.rs
We recently refactored the `TranslatePk` traits but did not do _all_ the implementations.
- Patch 1 trivial cleanup.
- Patch 2 does the remaining implementations.
- Patch 3 shortens other instances of the `translatefpk[h]` identifier so as to be uniform.
=> Refactor implementations of `TranslatePk`

src/miniscript/context.rs, src/miniscript/mod.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs
- Instead of explicitly counting all opcodes required while satisfaction,
we explicitly track only additional opcodes while satisfaction and
dissatisfaction.
- Removes some unnecessary code around wrapper casting
Double-checked and compared with the c++ codebase
=> Refactor opcode calculations

src/descriptor/key.rs, src/descriptor/mod.rs
As we have been doing in `rust-bitcoin` attempt to use idiomatic names for our conversion functions.
Re-name the key conversion functions `as_public` to be `to_public` because they take a borrowed type and return an owned, non-Copy type.
While we are it at do a bunch of refactoring to the individual functions. Each done as a separate patch, can drop any not wanted.
=> Re-name `as_public` -> `to_public`

examples/htlc.rs, examples/parse.rs, examples/sign_multisig.rs, examples/verify_tx.rs, examples/xpub_descriptors.rs
In an effort to make the examples more digestible to newcomers do various clean ups and refactorings. Each example is done as a separate patch to assist review.
The diffs get smaller as you go down the list :)
=> Clean up the examples

examples/htlc.rs, examples/parse.rs, examples/psbt.rs, examples/sign_multisig.rs, examples/verify_tx.rs, src/lib.rs, src/miniscript/mod.rs
Now we have edition 2018 we can remove the usage of `extern crate`.
- Patch 1 does the `examples/`
- Patch 2 does the docs
- Patch 3 does the main crate
=> Remove extern crates

integration_test/Cargo.toml, integration_test/src/main.rs, integration_test/src/test_util.rs
As we did for the main crate, enable edition 2018 in the `integration_test` crate.
=> integration_test: Enable edition 2018

examples/verify_tx.rs
This comment is stale, we no longer have `to_pk_ctx` in the codebase.
=> Remove stale comment

src/descriptor/key.rs, src/expression.rs, src/interpreter/stack.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/mod.rs, src/miniscript/types/extra_props.rs, src/policy/compiler.rs
Clear all the remaining non-controversial clippy warnings.
Should be just the curly ones left after this.
=> Clear some more clippy warnings

.github/workflows/rust.yml, contrib/test.sh, src/descriptor/key.rs, src/descriptor/mod.rs, src/interpreter/mod.rs, src/psbt/mod.rs
First fix all the docs build errors then enable docs build in CI, as we do in other crates in our stack.
=> Enable building docs in the CI pipeline

src/descriptor/key.rs, src/descriptor/mod.rs
After a brief chat on IRC and in PR #339, here's a quick draft for a new type specific to derived `DescriptorPublicKey`s.
This is the same design we use in BDK, where we wrap a normal `DescriptorPublicKey` and a secp context in a new struct. This has the drawback that the struct carries a lifetime and generic for the ctx, but I couldn't think of any other way to get this to work unless we drop the implementation of `ToPublicKey` for `DerivedDescriptorKey` which in my opinion can be very useful.
=> Define a new type for derived `DescriptorPublicKey`s

src/descriptor/key.rs
Clippy emits:
warning: very complex type used. Consider factoring parts into `type` definitions
The type we return is more complex than needed because we do not use the `bip32::KeySource` alias but instead write the full tuple `(byp32::Fingerprint, bip32::DerivationPath)`.
To fix the clippy warning we have at least 3 options
1. Add an alias for the complex return type
2. Add a compiler directive to quieten clippy
3. Use `bip32::KeySource` instead of tuple
(1) seems like an overkill
(2) means we loose lint coverage for the whole function
Elect to do (3), the best of 3 imperfect solutions.
=> Use KeySource instead of tuple

.github/workflows/rust.yml, contrib/test.sh
Make an effort to improve the test script, taking inspiration for the test script in `rust-secp256k1`. Since Bash can, at times, be a bit obscure, I made extra effort to do very simple discreet patches.
First part of the PR is fixes to the test script, second part is improvements to the CI pipeline.
=> Improve the test script and CI pipeline

src/miniscript/mod.rs
We manually implement a bunch of traits on `Miniscript` that pass through to the `node` field (e.g. `PartialEq`). We should do the same for `hash::Hash` instead of deriving it.
Found by clippy.
Fixes: #381
=> Implement hash::Hash for Miniscript

src/miniscript/mod.rs, src/miniscript/types/correctness.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/malleability.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs
Previously, the struct `CompilerExtData` provided cost analysis for a given script considering the **SegwitV0** standards. This PR aims to track the type/ (context) of the script and provide the respective cost analysis.
=> SigType check for cost-analysis in SegwitV1 scripts

src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs
This PR builds on top of #278. 
This is one in a series of PRs aimed to implement a feature-complete *Pay-to-Taproot* **P2Tr** compiler.
Specifically, this introduces a basic compilation for a given policy by collecting the leaf nodes of the *tree* generated by considering root-level disjunctive `OR`and using this to generate a `TapTree`. 
> Assuming that _duplicate keys_ are **NOT** possible even in different branches of the TapTree.
- #342  - Uses heuristic for tree-generation/ _merging_ algorithm while buillding `TapTree` to optimize over the *expected average total cost*. 
- #352 
- A future PR implementing enumerative strategies for optimizing `thresh` `k`-of-`n` and similar structures.
=> Taproot Compiler

src/interpreter/inner.rs
We have non-uniform function names, sometimes 'stackelem' is used and sometimes 'stack_elem'.
Be uniform and conventional, use 'stack_elem' in function names.
Fixes: #272
=> Rename stackelem to stack_elem

src/interpreter/inner.rs, src/miniscript/types/extra_props.rs
Do a few refactorings in an attempt to make the `threshold` method easier to read.
=> Refactor threshold method

src/interpreter/mod.rs, src/interpreter/stack.rs, src/miniscript/analyzable.rs, src/miniscript/limits.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/policy/concrete.rs, src/policy/mod.rs
Done while working on a [timelock module](https://github.com/rust-bitcoin/rust-bitcoin/pull/994). This is all the initial patches (except one) from https://github.com/rust-bitcoin/rust-miniscript/pull/408 (which is a PR displaying usage of the new timelock module).
Note, does _not_ do the 'make `TimelockInfo` fields pub crate' change - I was unsure if this was correct.
=> Improve timelock code

src/descriptor/mod.rs
Do minor grammar improvement. This is a nit from review of https://github.com/rust-bitcoin/rust-miniscript/pull/386#pullrequestreview-978253570
=> Fix grammar 'any' -> 'an'

src/descriptor/key.rs, src/interpreter/error.rs, src/lib.rs, src/miniscript/analyzable.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/psbt/mod.rs
Now we have MSRV of 1.41.1 we can implement `source` for improved error handling.
Patches 1-3 are preparatory cleanup, patch 4 adds all the `source` impls.
Resolves: #273
=> Implement `source` for error types

src/lib.rs, src/miniscript/types/mod.rs, src/policy/semantic.rs, src/timelock.rs
Currently if we mix up height/time absolute timelocks when filtering policies the result is incorrect (to the best of my understanding).
Add a `timelock` module that includes a single public function for checking if absolute timelocks are the same unit. Use the new function to fix a bug in policy filtering.
- Patch 1 is a docs bug fix
- Patch 2 is the bug fix
- Patch 3 is a unit test patch that fails if its moved before patch 2. Please review the unit test carefully to make sure I'm not confused.
There is [ongoing discussion](https://github.com/rust-bitcoin/rust-bitcoin/pull/994) around trying to design a suitable timelock API. This PR is an attempt to make some forward progress by taking baby steps _and_ making objective improvements. I decided to do it here in miniscript because it will …
=> Fix bug in absolute timelock usage

src/descriptor/tr.rs
=> Fix TapTree depth check bug

src/interpreter/mod.rs, src/interpreter/stack.rs, src/policy/semantic.rs, src/psbt/finalizer.rs
We currently use age/height as identifiers for values related to CLTV and CSV. However we get them mixed up in the function call to `from_txdata`. Do a few improvements to fix the mixup and improve the overall situation.
- Patch 2 is a breaking change, changes a public method name. 
- Patch 1 an 4 are bug fixes.
(This description and PR are totally re-written, the comment directly below is now stale.)
=> Fix up mixup of age/height

tests/setup/test_util.rs, tests/test_desc.rs
- Earlier we did not have the ability to write integration tests that fail.
- The default behaviour was to panic and stop the execution of the program. 
- But in addition to verifying that the code works in the correct cases, we must also ensure that it should generate an appropriate error in incorrect cases.
- Some functions are modified to return Result<T, E> to support this feature.
- Four failing tests have also been added (tests 10-13) to demonstrate this.
=> Add support for writing integration tests that fail

src/policy/concrete.rs
This PR works on top of  #291 and #342. It introduces a new function `compile_to_descriptor` which requires a `DescriptorCtx` (suggestions for a better enum name are welcome!) allowing directly compilation of a policy into the specified descriptor type.
=> Allow direct compilation of a Policy into a valid Descriptor

examples/taproot.rs, src/descriptor/bare.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/descriptor/tr.rs, src/interpreter/mod.rs, src/interpreter/stack.rs, src/lib.rs, src/macros.rs, src/miniscript/astelem.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/miniscript/hash256.rs, src/miniscript/iter.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs, src/psbt/mod.rs, src/test_utils.rs, tests/setup/test_util.rs, tests/test_cpp.rs, tests/test_desc.rs
- Implement a new hash type that does not display/FromStr with `DISPLAY_BACKWARD`. Should we make this type upstream in bitcoin-hashes?
- Remove the PkTranslator trait as it was causing conflicting implementations downstream. 
- Replace the above with more macros :(
=> Add Hash256 associated type

src/lib.rs
We cast `u32` to `usize` in a bunch of places, this will cause strange behaviour because of truncation on 16 bit architectures.
Add a compile time check to explicitly not support 16 bit architectures.
=> Explicitly do not support 16 bit architectures

examples/xpub_descriptors.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/lib.rs, src/psbt/mod.rs, tests/test_desc.rs
This PR further develops the idea introduced in #345. It has two commits both with relatively detailed commit messages that can be reviewed separately. In summary:
1. Develop the `DerivedDescriptorKey` (a key that is guaranteed not to have wildcard in it) idea more by adding missing functionality and refining the API. In addition, I removed the error cases from `ConversionError` which seems to have been omitted from #345.
2. Since the introduction of `DerivedDescriptorKey`, the overlapping usage of the term "derive" has become quite confusing. In addition to the usual definition of "derive" we have also used it to mean "replace a wildcard with a particular derivation index". I deprecated and renamed everything that uses the latter definition.
=> DerivedDescriptor unfinished business

Cargo.toml, contrib/test.sh, src/lib.rs
As we did in `rust-bitcoin`; change the "serde" feature to
"actual-serde" and use `package = "serde"`. This allows users of
miniscript to use "serde" as the feature enabling serde instead of our
custom "use-serde".
Fix: #438
=> Add feature "serde"

fuzz/Cargo.toml, fuzz/travis-fuzz.sh
Looks like fuzzing is broken.
Disable `hongfuzz` default features as we did in `rust-bitcoin`.
=> Disable honggfuzz features

README.md, contrib/test.sh
A recent release of `form_urlencoded` breaks our test run when using 1.41.1 toolchain.
Pin the `url` and `form_urlencoded` dependencies when on 1.41.1 toolchain. Add a section to the readme instructing devs how to pin relevant dependencies (only when running tests).
=> Pin dependencies when using MSRV

contrib/test.sh, src/lib.rs
Also derive `Default` for `DummyHash` and all of its hash types since they are all empty structs.
=> Fix inconsistent naming in the dummy key hash structs

src/lib.rs, src/policy/concrete.rs, src/policy/mod.rs
This PR is a follow-up in the Tr-compiler series. This introduces splitting of a `thresh(k, ...n...)` policy into different Tapleaves. 
> For now, kindly refer to the code documentation and comments for the strategy implemented
=> Tr compiler v3 - Incremental Enumerative Compiler

fuzz/fuzz_targets/compile_descriptor.rs
=> fuzz: fix `compile_descriptor` to sort lifted policies before comparing

src/psbt/mod.rs
This essentially mirrors `PsbtInputExt::update_with_descriptor` but it works on PSBT outputs.
To avoid code duplication, the current logic that deals with PSBT inputs has been generalized to handle both input and outputs with a new internal `PsbtFields` trait.
-----
I hope it's not too late to get this PR in the new 8.0 release (cc #462)
=> Add `PsbtOutputExt::update_with_descriptor`

src/miniscript/context.rs
The `pk_len()` returned should account for the extra byte for the OP_PUSH opcode. This is true for all the other contexts, but not for `BareCtx`, so this commit fixes it.
------
This PR is based on the `7.0.0` tag because in my opinion it's worth applying this and releasing as `7.0.1` without waiting for `8.0.0` (BDK would naturally benefit from this because we are about to make one new release still based on `7.0.0` and it's tricky to workaround this issue in our code).
I think the patch is small enough that it can easily be applied on older releases as well, if you want to backport it too.
=> Fix `pk_len()` for `BareCtx`

examples/taproot.rs, src/descriptor/tr.rs
* Key spend path should take into consideration the scriptSigLen, stackLen and itemLen (for the one and only stack item).
* Script spend path should consider `control_block` and `script` to be items on the stack.
I also restructured the function to improve readability.
=> Fix `max_satisfaction_weight` calculations for taproot.

src/descriptor/bare.rs, src/descriptor/checksum.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/tr.rs
=> allow disabling the checksum with alternate `Display`

src/descriptor/key.rs
DescriptorPublicKey::derive_public_key API hit an unreachable line when
executing.
public_key.derive_public_key(&secp).unwrap_err();
This commit removes the API altogether and only exposes the method via
`DefiniteDescriptorKey`. Unfortunately, non-wildcard users would need
to pass a dummy value to .at_derivation_index to get this struct, but I
think this is okay.
=> Fix unreachable code from calling derive_public_key

CHANGELOG.md, Cargo.toml
Draft release PR. Still blocked on reviews of
1) #418 
2) #450 
3) #461
=> Release 8.0.0

CHANGELOG.md, Cargo.toml, contrib/test.sh, examples/psbt_sign_finalize.rs, src/miniscript/astelem.rs, src/miniscript/satisfy.rs, src/psbt/mod.rs
- Cleanup some pkh code in satisfaction
- Fixes #483
- Fixes another bug dealing with dissatisfaction of thresh inside pkh
- Adds example test vector from discussions
- release 9.0.0 with above fixes
=> Release 9.0.0

src/descriptor/key.rs, src/descriptor/mod.rs
The public key types (`DescriptorPublicKey`, `DescriptorXKey`, `SinglePubKey`, and `DefiniteDescriptorKey`) all have comparison derivations.
The underlying private key types (`bitcoin::PrivateKey`, `Fingerprint`, `DerivationPath`, `DescriptorXKey`, and `ExtendedPrivKey`) all have comparison derivations.
Let's catch 'em all.
=> Derive comparison traits for all secret key types

src/descriptor/key.rs, src/descriptor/mod.rs, src/interpreter/mod.rs, src/lib.rs, src/psbt/mod.rs, tests/test_desc.rs
This implements [BIP389 multipath descriptors](https://github.com/bitcoin/bips/pull/1354). Fixes #469.
=> Multipath descriptors

src/interpreter/mod.rs
We no longer have the MSRV 1.29 - no need to support it.
=> Remove support for 1.29

src/descriptor/mod.rs, src/miniscript/types/extra_props.rs
Done in an effort to clear all clippy warnings.
Add two allow attributes to quieten clippy. This may not be the best solution but it at least flags the code for future improvement and allows us to enable clippy in CI (along with other clippy work).
=> Use allow attribute

src/interpreter/mod.rs
Clippy emits:
warning: methods with the following characteristics: (`to_*` and `self`
type is `Copy`) usually take `self` by value
The method in question is private, change to take `self` by value. Requires no other changes.
(Should have been part of the trivial clippy fixes :)
=> Take self by value

contrib/test.sh, src/descriptor/key.rs, src/descriptor/mod.rs, src/interpreter/stack.rs, src/lib.rs, src/miniscript/decode.rs, src/policy/concrete.rs
Make an effort to do some docs improvements without touching the whole codebase.
- Patch 1: Trivial, because I can't help myself.
- Patch 2: Clean up docs on a private method in preparation for duplicating in public docs
- Patch 3: Fix broken links and enable `-D rustdoc::broken-intra-doc-links` in CI
I'm in no way across this codebase, there may be other problems with docs that show up in this PR but the PR is an attempt at improving the docs without going too wild - both for my sanity and that of reviewers.
=> Enable `-D rustdoc::broken-intra-doc-links`

fuzz/fuzz_targets/compile_descriptor.rs, fuzz/fuzz_targets/roundtrip_concrete.rs, fuzz/fuzz_targets/roundtrip_descriptor.rs, fuzz/fuzz_targets/roundtrip_miniscript_str.rs, fuzz/fuzz_targets/roundtrip_semantic.rs, src/descriptor/mod.rs, src/lib.rs, src/miniscript/mod.rs, src/policy/compiler.rs, src/policy/mod.rs
An alternative to #500 (because I just saw the issue #437)
As described in issue #437 we can use `String` in place of the `DummyKey` in all current test use cases.
Use `String` in tests and remove the `DummyKey` along with all the other (currently unused) `DummyFoo` types.
Fix: #437
=> Remove `DummyKey`

src/miniscript/decode.rs, src/policy/concrete.rs
I merged #507 without checking CI, and it turns out there was a rustfmt issue. FIx that.
=> fix formatting after #507

Cargo.toml, contrib/test.sh
Add a "base64" feature that enables the `base64` dependency in `rust-bitcoin`. This enables `Psbt::from_str()`.
Fix: #480
=> Add base64 feature

src/descriptor/key.rs
Fixes #491 
I didn't provide a mutable version of this. I'm not sure if we want to support this or not; generally public keys should be immutable after creation.
=> DefiniteDescriptorKey: provide additional methods for converting to a DescriptorPublicKey

embedded/src/main.rs, examples/psbt_sign_finalize.rs, examples/sign_multisig.rs, examples/taproot.rs, src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/tr.rs, src/lib.rs
Replaces #474, refer to https://github.com/rust-bitcoin/rust-miniscript/pull/474#issuecomment-1272475306
This PR has two intentions:
1. Redefine `max_satisfaction_weight` to be the difference in `TxIn` weight between "satisfied" and "unsatisfied" states. In an "unsatisfied" state, we still need to include the `scriptSigLen` varint, as well as the `witnessStackLen` (for txs with at least one segwit spend).
2. Attempt further fixes to improve accuracy of `max_satisfaction_weight`.
Comments, tests and examples have been updated to reflect the above intentions.
The new definition of `max_satisfaction_weight` can be seen in this comment:
https://github.com/rust-bitcoin/rust-miniscript/blob/08cff39fa862ff957c7ff96d17a0011dd6446f87/src/descriptor/mod.rs#L320-L339
=> Another attempt at `max_satisfaction_weight` fixes

src/miniscript/types/extra_props.rs
This TODO was actually from 255 where the bug was in cast_unlikely, even though the issue is labeled with or_i (my bad for not checking). There is no code for `cast_unlikely` as it is treated as or_i.
Addressed in 239efd55387f1d893e6ac4e602ca11454785c375
Fixes #268
=> Remove fixed TODO

contrib/test.sh, src/test_utils.rs
Fixing `StrKeyTranslator` in `test_utils.rs` where Z was not included. 
Closes #496 
Signed-off-by: Harshil Jani <harshiljani2002@gmail.com>
=> Fixing the Inclusivity of Z in StrKeyTranslator

Cargo.toml, src/descriptor/key.rs
Save me from ever writing the following code again:
```rust
pub mod serde_descriptor_key {
use std::str::FromStr;
use miniscript::DescriptorPublicKey;
use serde::{Deserialize, Deserializer, Serializer};
pub fn serialize<S>(dpk: &DescriptorPublicKey, serializer: S) -> Result<S::Ok, S::Error>
where
S: Serializer,
{
serializer.serialize_str(&dpk.to_string())
}
pub fn deserialize<'de, D>(deserializer: D) -> Result<DescriptorPublicKey, D::Error>
where
D: Deserializer<'de>,
{
let s = String::deserialize(deserializer)?;
DescriptorPublicKey::from_str(&s).map_err(serde::de::Error::custom)
}
}
```
=> Serde for DescriptorPublicKey

src/miniscript/mod.rs, src/miniscript/types/correctness.rs, src/miniscript/types/malleability.rs, src/miniscript/types/mod.rs, tests/test_desc.rs
While we are at it, do not use the default impl. This makes these types
of errors easy to make. I think this could have easily been prevented if
I was forced to explicitly write AnyNonZero in front of multi_a.
Reported by darosior.
=> Update multi_a to not include n wrapper

README.md, src/lib.rs
Building this crate requires the std and/or no-std features be enabled. This PR documents this build constraint in the README and gives an error is anyone tries to build without enabling one or both of these features.
See discussion in #533.
=> Add build error and README docs for proper use of std and no-std features

Cargo.toml, bitcoind-tests/Cargo.toml, bitcoind-tests/tests/setup/mod.rs, bitcoind-tests/tests/setup/test_util.rs, bitcoind-tests/tests/test_cpp.rs, bitcoind-tests/tests/test_desc.rs, contrib/test.sh, embedded/Cargo.toml, embedded/src/main.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/compile_descriptor.rs, fuzz/fuzz_targets/parse_descriptor.rs, fuzz/fuzz_targets/parse_descriptor_secret.rs, fuzz/fuzz_targets/roundtrip_concrete.rs, fuzz/fuzz_targets/roundtrip_descriptor.rs, fuzz/fuzz_targets/roundtrip_miniscript_script.rs, fuzz/fuzz_targets/roundtrip_miniscript_str.rs, fuzz/fuzz_targets/roundtrip_semantic.rs
This brings the fuzztests and bitcoind-tests into workspaces along with the root crate. This means they are covered by `cargo test --all` and `cargo fmt --all` without any special action, and also means that `crate2nix` can test them independently without my manually messing around with directories. I run `cargo +nightly fmt` to bring the two new workspaces into proper formatting -- there were no changes that I'd consider controversial.
It also allows the `bitcoin-tests` directory to be run with a custom `BITCOIND_EXE` variable, and computes the default version more flexibly so that you can run the tests from any directory.
Finally I set the minimum honggfuzz version to 0.5.55, since the dep currently was set to 0.5.0, which definitely did not work.
With these changes, everything in this …
=> Various fixes for Nix compatibility

src/interpreter/mod.rs
- Per https://github.com/rust-bitcoin/rust-miniscript/issues/543 `Bare` script should be legacy.
=> Fixed a bug where Bare script is_legacy

bitcoind-tests/tests/setup/test_util.rs, src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/descriptor/tr.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/context.rs, src/miniscript/mod.rs, src/policy/compiler.rs, src/psbt/finalizer.rs, src/psbt/mod.rs
This PR has lot of cleanups that I had planned but did not have time for a long time. 
- All places now use constructors that do invariant checking on the struct being created. 
- Translate* APIs had a soundness bug you could create uncompressed keys in segwit descriptors etc.
=> update TranslatePk again

CHANGELOG.md, Cargo.toml
- Compatible with bitcoin 0.30.0
=> Release 10.0.0

Cargo.toml, src/policy/concrete.rs, src/policy/semantic.rs
=> Backport recursion fix to 7.x

src/miniscript/astelem.rs, src/miniscript/mod.rs, src/psbt/finalizer.rs
The PR adds up the method to convert the expr_raw_pkh into pkh by looking at the available keys and their hases being stored inside of the Hashmap of PSBT Input. If the key is found corresponding to given hash, It will update to pkh.
To-Do :
=> Add method to convert expr_raw_pkh into pkh

README.md, contrib/test.sh
Pin `serde_json` for 1.41 and 1.47 CI runs. Remove the pinning docs from the README and instead point devs to the CI script. (The docs are stale currently and are an unnecessary maintenance burden.)
=> Pin `serde_json`

src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs
Three patches, the first two simple. The third is a bunch of mixed rustdoc fixes. Just sing out if this is too painful to review. I did this while attempting to understand the module better.
=> policy: Do a bunch of docs fixes

Cargo.toml, README.md, contrib/test.sh, src/lib.rs, src/policy/compiler.rs, src/policy/mod.rs
Currently it is not possible to run the test suite with `cargo test --all-features`, this is because we use a feature called `unstable` to enable the unstable `test` crate that is used for benchmarking.
There is another way to conditionally enable the test crate and guard the benchmark code. We can use a custom configuration option `bench` and then set it using `RUSTFLAGS='--cfg=bench`.
=> Remove `unstable` feature

src/miniscript/satisfy.rs
We have various variants in this pattern that return the same thing, we can combine them to make the code more terse with no loss of clarity.
=> Combine terminal variants

src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/expression.rs, src/iter/mod.rs, src/iter/tree.rs, src/miniscript/analyzable.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/lex.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/correctness.rs, src/miniscript/types/malleability.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs, src/psbt/mod.rs
Recently we discussed in `rust-bitcoin` the pointlessness of the `\\ Written in ...` clause above the license terms. We came to the conclusion that:
- It probably wasn't written then and who cares anyway because we patch files all the time
- It almost certainly wasn't written by just this person because we have a bunch of contributors
- Use of "the rust bitcoin devs" is just noise and no signal
Remove the "written in" clause if it contains "the rust bitcoin devs" or Andrew's name (because he was part of the conversation in rust-bitcoin)
Do no remove clauses that have Sanket's name or Maxim's. Its up to them if they want attribution so we leave it there for now.
Leave Andrew's name in `lib.rs` as a little nod-of-the-head to him as the original author. I do not know the full relationship …
=> Remove written in clause

src/miniscript/mod.rs
Make an effort to clean up the `miniscript/mod.rs` file. I could not see a reason for all the separate impl blocks, is there one? Please note this PR does not fix all the docs, just does ones that should not be too hard to review.
=> Clean up `miniscript/mod.rs`

src/descriptor/mod.rs, src/descriptor/sortedmulti.rs, src/expression.rs, src/iter/mod.rs
All changes explained in their respective patch.
=> Do some random trivial fixes

src/interpreter/mod.rs, src/lib.rs
The trait method `MiniscriptKey::num_der_paths` often returns 0, lets just make this the default.
=> Add default impl for `Miniscript::num_der_paths`

CHANGELOG.md, Cargo.toml, src/policy/concrete.rs, src/policy/semantic.rs
Backport of #546. It looks like we only backported this to 7.x, not to 9.x or 8.x.
I'm not sure who is using 8.x. We should probably backport it there too. But 9.x (well, a slight fork of it) is used by elements-miniscript 1.0.
This is needed because Rust released a stable compiler with https://github.com/rust-lang/rust/issues/110475 even though it breaks code that compiled fine for years and there was an open issue for 3 months.
=> Backport recursion fix to 9.x

examples/taproot.rs, src/descriptor/tr.rs, src/policy/concrete.rs, src/policy/mod.rs, src/psbt/mod.rs
I stumbled across a `todo` in the code last week and thought I'd hack it up.
- Patch 1: Do identifier style fix
- Patch 2: Add a unit test to verify change in patch 3 is correct
- Patch 3: Remove recursive call to `tap_tree_height` 
From commit log of patch 3
Convert tuple `TapTree` tuple to a struct and add `height` to it. This
saves recusive call in `tap_tree_height` function.
While we are at it rename private function `TapTree::tap_tree_height` to
`TapTree::height` because it stutters.
=> Add height to tap tree

src/psbt/finalizer.rs
Recently , We have introduced the method `substitute_raw_pkh` to deal with the change of pkh to expr_raw_pkh. This is the implementation of that method for the taproot miniscript.
Reference PR : https://github.com/rust-bitcoin/rust-miniscript/pull/557
=> Adding substitution of pkh for taproot

Cargo.toml, src/descriptor/mod.rs, src/lib.rs, src/miniscript/analyzable.rs, src/miniscript/satisfy.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/psbt/finalizer.rs
We can use `BTreeSet` instead of `HashSet` and `BTreeMap` instead of `HashMap` to remove the `hashbrown` dependency.
=> Remove hashbrown dependency

src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs
The binary sizes are increased a lot by the use of generics. In one case, there is a lot of needless bloat by using a generic type param for the callback argument in the type_check function of the Property trait.
cargo build --example parse --release && du -sb target/release/examples/parse
Results in a binary size of 1784152 bytes.
With this commit, the binary size is decreased by 12288 bytes, which is significant for embedded/no_std use.
The sizes above were achieved by adding this to Cargo.toml:
```
[profile.release]
strip = true
panic = "abort"
opt-level = 's'
codegen-units = 1
lto = true
```
Though the difference is roughly the same also without the optimizations.
As an additional benefit, code clarity is improved as the child arg was unused in some of the trait implementations.
=> reduce binary bloat by removing generic param from type_check

src/descriptor/mod.rs
Fixes the `Txin` typo in the `max_weight_to_satisfy` to correct `TxIn`
I've noticed this while browsing the docs.
=> fix: Typo in descriptor docs

contrib/test.sh
Recently `memchr` broke our MSRV by updating to edition 2021 in a patch version, pin it in CI for MSRV builds.
=> CI: Pin memchr

bitcoind-tests/tests/test_cpp.rs, src/descriptor/bare.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/descriptor/tr.rs, src/lib.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/plan.rs, src/util.rs
This PR builds on top of #481, fixing all the review comments.
I didn't squash my last commits on purpose to make review easier, I can squash them before merging if preferred.
=> Add the planning module (updated PR)

src/iter/mod.rs, src/miniscript/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs
Make a start on removing recursion in the `policy::concrete` module.
- Patch 1: Remove`PolicyArc`
- Patch2: Implement `TreeLike` for `concrete::Policy` (does not use it)
- Patch 3: Trivial code comment deletion
- Subsequent patches are pairs
- Add a basic unit test for the function we are about to patch
- Remove recursion from a function (the one we just tested)
- Final patch is a refactoring 
There is still some to go but this is already a pretty heavy review burden.
=> Implement `TreeLike` for `policy::Concrete`

src/policy/concrete.rs
It is not immediately obvious that the `Concrete::And` and `Or` vectors contain exactly 2 elements, add code comment to document it.
=> Document And/Or vectors contain 2 elements

Cargo.toml, src/policy/concrete.rs, src/policy/semantic.rs
I think this is the last of the rust-miniscript versions in common use.
=> Backport recursion fixes to 8.x

src/policy/concrete.rs
Remove the last of the recursion in functions that process policies. Note there is still recursion in the `from_tree_prob` function that creates the policies.
=> Remove more recursion from `concrete::policy`

src/descriptor/checksum.rs
The first 4 patches from #608, no changes.
Clean up and add some test vector unit tests.
=> Do some `checksum` module improvements

.github/workflows/fuzz.yml, fuzz/Cargo.toml, fuzz/generate-files.sh
CI is complaining:
package `regex v1.10.0` cannot be built because it requires rustc 1.65
or newer, while the currently active rustc version is 1.64.0
Bump rustc to v1.65 in the `generate_files.sh` script and run it.
=> fuzz: Bump rustc to version1.65

Cargo.toml, src/descriptor/bare.rs, src/descriptor/checksum.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs
This is just the last patch, the rest are in #609 now.
The `checksum::poly_mod` function implements BCH codes to calculate a checksum (appended to descriptors). We recently released a version of BCH codes in `bech32`. We can implement the `bech32::Checksum` trait for BIP-380 and use the `primitives::checksum` module, removing the custom `poly_mod` function.
=> Use `bech32` to calculate descriptor checksums

src/policy/semantic.rs
The `_translate_pk` helper function adds nothing to the code. It comes from a day past when the signature of `translate_pk` and `_translate_pk` differed (see commit ef1d69c81e3acc34ed2ce71b6484d719cc631ab6).
=> Remove unnecessary helper function

src/descriptor/tr.rs
Improve the `TapTree` API by making the `height` and `combine` methods public.
Note the serendipitous finding that upgrading miniscript to use bitcoin v0.31.0-rc1 requires no changes. I found these fixes doing the `bdk` upgrade.
=> Improve `TapTree` API

clippy.toml, src/descriptor/checksum.rs, src/descriptor/key.rs, src/descriptor/tr.rs, src/iter/mod.rs, src/lib.rs, src/miniscript/types/extra_props.rs, src/plan.rs, src/psbt/finalizer.rs
=> Fix a bunch of clippy lints

Cargo.toml, bitcoind-tests/Cargo.toml, bitcoind-tests/tests/setup/test_util.rs, bitcoind-tests/tests/test_cpp.rs, bitcoind-tests/tests/test_desc.rs, examples/psbt_sign_finalize.rs, examples/sign_multisig.rs, examples/taproot.rs, examples/verify_tx.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/interpreter/error.rs, src/interpreter/inner.rs, src/interpreter/mod.rs, src/lib.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/plan.rs, src/policy/compiler.rs, src/psbt/finalizer.rs, src/psbt/mod.rs, src/test_utils.rs, src/util.rs
Upgrade `rust-bitcoin` to version 0.31.0 and also other required dependencies from our stack:
- secp256k1: to v0.28.0
- internals: to v0.2.0
- bitcoind: to v0.34.0
=> Upgrade bitcoin dependency

CHANGELOG.md, Cargo.toml
=> Tracking PR for release `v11.0.0`

Cargo.toml, bitcoind-tests/Cargo.toml, bitcoind-tests/tests/setup/test_util.rs, src/interpreter/error.rs, src/lib.rs
We do not need to depend on `internals` anymore, this was just needed until we sorted out `DisplayHex` in `hex-conservative`. This change should have been done as part of upgrading to `rust-bitcoin v0.31`.
=> Remove internals dependency

src/descriptor/sortedmulti.rs, src/descriptor/tr.rs, src/iter/mod.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs
Remove most of the recursion in the `semantic` module. Does not do `normalized` and associated functions (ones that either call it or take in a normalized policy). 
Includes 4 trivial preparatory clean up patches at the front.
=> Remove recursion in `semantic` module

.github/workflows/rust.yml, README.md, clippy.toml, contrib/test.sh
Following `rust-bitcoin` MSRV of 1.56.1, this pins MSRV to 1.56.1.
Quoting a recent merge in `rust-bitcoin`
> Rust version 1.56.0 introduced edition 2021. Shortly afterwards, on
> October 21 2021 Rust version 1.56.1 was released.
>
> Debian stable is currently shipping `rustc 1.63.0`.
>
> Our stated MSRV policy is: In Debian stable and at least 2 years old.
>
> Therefore our MSRV policy is met by Rust version 1.56.1 and we can strat
> to bump our MSRV org wide.
>
> Links:
> - https://blog.rust-lang.org/2021/11/01/Rust-1.56.1.html
> - https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html
> - https://packages.debian.org/stable/rust/rustc
Removing the pins in `contrib/test.sh` since they are not necessary
in 1.56.1.
EDIT: CI fails because of the `#[allow(dead_code)]` implemented in #638 on …
=> Update MSRV to 1.56.1

src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/tr.rs, src/psbt/mod.rs
Adds a `since=10.0.0` to all `max_satisfaction_weight` deprecations. Adds a note telling users to check #476 for more details.
Closes #637.
=> Deprecate across the board `max_satisfaction_weight`

examples/verify_tx.rs, examples/xpub_descriptors.rs, src/descriptor/mod.rs, src/interpreter/inner.rs, src/interpreter/mod.rs, src/plan.rs, src/policy/semantic.rs, src/psbt/mod.rs, src/test_utils.rs
Nothing out of the ordinary.
The most alarming was the non-inclusive range in
`test_utils.rs`.
In some test functions I allowed myself to use
`#[allow(clippy::type_complexity)]` because clippy was asking to create a type instead of using the big tuple. Since these were used just once, I thought it was overkill.
Note, depends on:
- #639 (we can also merge this into it instead of `master`)
- #638 (has some allows on dead_code)
=> Clippy lints MSRV 1.56.1

examples/psbt_sign_finalize.rs, examples/sign_multisig.rs, examples/verify_tx.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/descriptor/tr.rs, src/interpreter/error.rs, src/interpreter/inner.rs, src/interpreter/mod.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/iter.rs, src/miniscript/mod.rs, src/plan.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs, src/psbt/finalizer.rs, src/psbt/mod.rs, src/test_utils.rs
This error would trigger on `l:0` on the basis that this is equivalent to `u:0` but always less efficient. There are no other "linting" errors like this in this library, and the C++ implementation doesn't have it, so we should drop it.
Fixes #633
=> remove sketchy `LikelyFalse` error

Cargo.toml, examples/big.rs
Tools like `cargo bloat` don't work on libraries but on final executable.
As seen in https://github.com/rust-bitcoin/rust-miniscript/issues/585 and https://github.com/rust-bitcoin/rust-miniscript/pull/584 the parse example is used as a base to profile binary bloat.
However, since the parse example is not using all the API surface, we may have good optimization that are not recognized as such because the optimized function are not in the tree of the functions used.
For benchmarking size optimization a specific binary that ideally touch all the API surface is needed and this MR introduce it.
More coverage will be added if this seem a good idea for reviewers.
=> Introduce an example binary useful for profiling

src/blanket_traits.rs, src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/tr.rs, src/miniscript/astelem.rs, src/miniscript/mod.rs, src/miniscript/types/correctness.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/malleability.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/semantic.rs
Something of a followup to #649, which specifically removes the `type_check` method from `Property`.
Basically, this whole trait is confused. Originally it was supposed to express "a recursively defined property of a Miniscript" which could be defined by a couple constructors and then automatically computed for any Miniscript. In fact, the trait required a separate constructor for every single Miniscript fragment so nothing was "automatic" except sometimes reusing code between the different hash fragments and between `older`/`after`.
Furthermore, every implementor of this trait had slightly different requirements, meaning that there were `unreachable!()`s throughout the code, functions that were never called (e.g. `Type::from_sha256` passing through to `Correctness::from_sha256` and …
=> Drop the `Property` trait entirely

src/miniscript/astelem.rs, src/miniscript/mod.rs
fmt functions produce big binaries.
<details>
<summary>cargo bloat --release --example big --all-features -n 1000000 --full-fn | grep astelem | grep fmt</summary>
0.0%   0.1%  2.8KiB       miniscript miniscript::miniscript::astelem::<impl core::fmt::Debug for miniscript::miniscript::decode::Terminal<Pk,Ctx>>::fmt::h75ba3ce6da61d374
0.0%   0.1%  2.8KiB       miniscript miniscript::miniscript::astelem::<impl core::fmt::Debug for miniscript::miniscript::decode::Terminal<Pk,Ctx>>::fmt::h6786aa26184b9ff6
0.0%   0.1%  2.8KiB       miniscript miniscript::miniscript::astelem::<impl core::fmt::Debug for miniscript::miniscript::decode::Terminal<Pk,Ctx>>::fmt::h03f9c2155559a440
0.0%   0.1%  2.8KiB       miniscript miniscript::miniscript::astelem::<impl core::fmt::Debug for …
=> add conditional formatting for Terminal

examples/taproot.rs, src/descriptor/sortedmulti.rs, src/descriptor/tr.rs, src/lib.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/limits.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs
The compiler logic when encountering thresholds of pks is currently a bit confused, and therefore chooses multi/multi_a in cases where this is not the most efficient compilation.
This PR fixes that, and also brings in a few other cleanup commits that I had laying around.
This does **not** fix #656, which I didn't know how to approach.
=> compiler: improve logic when deciding between conjunctions and multi/multi_a

src/interpreter/inner.rs, src/interpreter/mod.rs, src/miniscript/analyzable.rs, src/miniscript/lex.rs, src/miniscript/satisfy.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs
This commit dervies `Hash` for enums and structs which also derives `Eq`.
Fixes #226
=> Derives `Hash` for pub items

Cargo.toml, src/descriptor/checksum.rs
Upgrade to the newest release of the `bech32` crate.
=> Upgrade bech32 dependency

embedded/src/main.rs, examples/sign_multisig.rs, examples/taproot.rs, src/descriptor/bare.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/tr.rs, src/lib.rs
Return Weight type for max_weight_to_satisfy methods.
=> Return Weight type for max_weight_to_satisfy methods

src/interpreter/mod.rs
The `interpreter::BitcoinKey` uses the default implementation of `MiniscriptKey`, which means `is_uncompressed` returns `false`. However if the full key is a `bitcoin::PublicKey` it may be compressed.
Manually implement `MiniscriptKey::is_uncompressed` for `BitcoinKey` and return the compressedness of the inner full key.
Originally done, and discussed, in #620.
=> Manually implement is_uncompressed for BitcoinKey

src/psbt/mod.rs
When building the rustdocs clippy emits:
warning: redundant explicit link target
As suggested, remove the explicit link target. Do not fix column width because this rustdoc block is already a mess - just make the change while keeping the diff small.
=> Remove explicit link target

examples/psbt_sign_finalize.rs, examples/taproot.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs
After doing #668 I wanted to be able to use the `just sane` command before pushing PRs, so fix the lint issues.
=> Fix all lint errors and warnings

.github/workflows/rust.yml, contrib/test.sh, src/lib.rs
We are not currently running the linter in CI, do so.
=> CI: Lint the crate and examples

src/descriptor/mod.rs, src/descriptor/sortedmulti.rs, src/interpreter/mod.rs, src/miniscript/astelem.rs, src/miniscript/context.rs, src/miniscript/decode.rs, src/miniscript/iter.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs
Some more large but mostly-mechanical diffs. This is able to eliminate a bunch of error paths, though the actual error variants can't be removed until we also convert Terminal::thresh in the next PR(s). At that point we will start to see the real benefits of this type because fallible functions will become fallible and massive amounts of compiler error-checking can just go away entirely.
Also removes the allocation in `SortedMulti::constructor_check` that was pointed out in #660.
=> Use `Threshold` type in concrete policy and in Terminal::multi/multi_a

src/descriptor/mod.rs, src/interpreter/mod.rs, src/iter/mod.rs, src/miniscript/astelem.rs, src/miniscript/decode.rs, src/miniscript/iter.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/miniscript/types/extra_props.rs, src/miniscript/types/mod.rs, src/policy/compiler.rs, src/policy/mod.rs
This completes the "threshold" conversion and completely drops the various ad-hoc error paths related to threshold values (most of which were just random strings).
The next set of PRs will be related to cleaning up errors in general a bit, to strongly-type things and add span information. But I am struggling a bit with how to box the associated error types for the MiniscriptKey types so it may be a while. (Very hard to do this in a std/nostd compatible way and the final result will probably be inconvenient/annoying for users.)
=> Use threshold in Terminal and Satisfaction

contrib/test.sh
The `cc` dependency just stopped working for MSRV build with error
error: package `cc v1.0.96` cannot be built because it requires
rustc 1.63 or newer, while the currently active rustc version is
1.56.1
Pin `cc` back to an earlier version for MSRV build.
=> CI: Pin cc for MSRV build

bitcoind-tests/tests/setup/test_util.rs, bitcoind-tests/tests/test_cpp.rs, bitcoind-tests/tests/test_desc.rs
All the clippy patches rom #682, only touches `bitcoind_test`.
=> bitcoind_test: Fix clippy

Cargo.toml, bitcoind-tests/Cargo.toml, bitcoind-tests/tests/test_cpp.rs, bitcoind-tests/tests/test_desc.rs, examples/psbt_sign_finalize.rs, examples/sign_multisig.rs, examples/verify_tx.rs, src/descriptor/bare.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/interpreter/error.rs, src/interpreter/mod.rs, src/lib.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/policy/compiler.rs, src/psbt/finalizer.rs, src/psbt/mod.rs
We just released a new version of `bitcoin`, lets use it.
Includes upgrading the version of:
- `bitcoind` to `v0.36.0`
- `secp256k1` to `0.29.0`
=> Upgrade to `bitcoin v0.32.0`

.github/workflows/shellcheck.yml, embedded/scripts/env.sh, fuzz/cycle.sh, fuzz/fuzz.sh, fuzz/generate-files.sh
Following https://github.com/rust-bitcoin/rust-bitcoin/pull/2762,
adding CI shellcheck cheks here as well.
I also did all fixes that I could find with
```bash
shellcheck **/*.sh
```
If I've missed any please let me know.
=> ci: shellcheck checks

CHANGELOG.md, Cargo.toml
In preparation for release add a changelog entry and bump the version.
=> Release tracking PR: `v12.0.0`

src/lib.rs, src/plan.rs
It looks like we have an example AssetProvider that is intended to be used for testing/debugging. It looks useful but evidently has never been used because it was impossible to construct.
Recent versions of rust nightly notice this and output a warning about this, which is causing CI to fail, so we need to fix it.
My solution is to make the inner `Assets` public (and also a reference, since there is no need to take ownership) so that people can easily construct and deconstruct the type.
=> plan: make LoggerAssetProvider constructible

CHANGELOG.md, Cargo.toml
Turns out there were only two tiny changes in the last six months. One changes the API so this is a minor bump rather than a patch bump.
=> release 12.1.0

CHANGELOG.md, Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, src/miniscript/decode.rs, src/miniscript/mod.rs
Use private module to guard all constructors.
=> Fix panic while decoding large Miniscripts from Script

.github/workflows/README.md, .github/workflows/rust.yml, Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, bitcoind-tests/Cargo.toml, bitcoind-tests/tests/setup/mod.rs, bitcoind-tests/tests/test_cpp.rs, bitcoind-tests/tests/test_desc.rs, contrib/crates.sh, src/lib.rs
There is an effort to improve the state of affairs in regards to integration testing extensively against multiple versions of Bitcoin Core. As part of this do:
- Depend on the new `rust-bitcoind-json-rpc` crates
- Run the integration tests against most versions of Core since 0.17.1
(Note the latest supported version is currently 26.0)
ref: https://crates.io/search?q=bitcoind-json-rpc
=> Depend on the new bitcoind-json-rpc group of crates

.github/workflows/rust.yml
We don't want to pull the maintainer tools repo from master otherwise we cannot patch it, we should use a specific revision.
This was an oversite in the original work when introducing the maintainer tools `run_task` script.
Use commit:
b2ac115 Merge rust-bitcoin/rust-bitcoin-maintainer-tools#4: Add CI shell scripts
=> CI: Use specific revision of maintainer-tools

src/miniscript/decode.rs, src/miniscript/mod.rs
This is mostly just annoying/mechanical code. But it needs to be written because the derive(Clone) logic, I think, was only doing a "shallow clone" by cloning the Arcs in the Miniscript.
In my view this is undesirable behavior. If users want to do a shallow clone, they can hold an Arc<Miniscript> and call Arc::clone on that. But there are some cases where they might want to do a deep clone, and currently there isn't really any way to do so (you can do it with the translator API and an "identity" translator, but this is awkward to do and will be slow because it redoes typechecking and rechecks for duplicate keys).
=> miniscript: non-recursive Clone

src/iter/tree.rs, src/miniscript/mod.rs, src/miniscript/types/mod.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs
This PR does a few things which are mostly related:
* Adds unit tests and does a couple cleanups.
* Introduces a new right-to-left post-order iterator and uses that to eliminate a bunch of Arc::clones and extra memory usage from existing non-recursive algorithms
* Fixes a bug in `Miniscript::substitute_raw_pkh` where the function completely didn't work (this fell out of the right-to-left change)
* Converts `Miniscript::lift` to be non-recursive
* Eleminates `Terminal::lift` because this impl is conceptually confused (`Terminal` as a type should never be used except to construct `Miniscript`s; they are not typechecked or sanity-checked and have no capacity to store type information). It was originally implemented as a convenience to help the `Miniscript` implementation but we don't need it …
=> Eliminate more recursion, and Liftable impl for Terminal

src/miniscript/context.rs, src/miniscript/satisfy.rs, src/miniscript/types/correctness.rs, src/miniscript/types/malleability.rs, src/miniscript/types/mod.rs, src/plan.rs, src/psbt/finalizer.rs, src/psbt/mod.rs
Also does a few miscellaneous fixes that I noticed while fixing the lint.
=> docs: fix new clippy lint about excessively long initial line

.github/workflows/cron-daily-fuzz.yml, fuzz/Cargo.toml, fuzz/fuzz_targets/compile_taproot.rs, fuzz/generate-files.sh, src/lib.rs, src/policy/compiler.rs, src/policy/concrete.rs, src/policy/mod.rs, src/policy/semantic.rs
Right now our Taproot compiler does some complicated analysis to identify a key within a policy that may be extracted to use as an internal key. Specifically, if you look at the "disjunction tree" at the root of a policy, every leaf of this tree can be a tapbranch and any leaf which is just a pubkey-check and nothing else is a candidate to be the internal key.
However, our logic to do this is convoluted, has many unnecessary error paths, and lots of gratuitous allocations (which ironically make the code harder, not easier, to follow).
This PR smooths all that out by introducing a new iterator over the potential tapbranches of a policy (along with their probabilities). It also cleans up much of the error handling in the policy module, eliminating 3 calls to the stringly-typed `errstr` …
=> Refactor `extract_key` logic in Taproot compiler

src/primitives/absolute_locktime.rs
Maximum absolute locktime is 2^31 - 1, not 2^31 in miniscript.
reference: https://github.com/bitcoin/bitcoin/blob/master/src/script/miniscript.h#L2281
=> fix: possible absolute locktime overflow error

bitcoind-tests/tests/setup/test_util.rs, examples/big.rs, examples/taproot.rs, src/descriptor/bare.rs, src/descriptor/key.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/descriptor/tr.rs, src/interpreter/inner.rs, src/lib.rs, src/miniscript/mod.rs, src/policy/concrete.rs, src/policy/semantic.rs, src/psbt/mod.rs, src/pub_macros.rs, src/test_utils.rs
This may be too much of a breaking change and an instance of https://github.com/rust-bitcoin/rust-bitcoin/issues/3166, but the existing traits are *really* annoying to use. But this change is not essential to any of my other work so feel free to concept NACK it.
There are two changes here:
* This drops the `TranslatePk` trait which had no business existing. It attempts to be generic over "things whose keys can be translated", but is missing impls (on keys themselves, for example) and anyway it is basically impossible to usefully be generic over this trait since it has an associated `Output` type which is unconstrained except by a comment saying "this must be `Self<Q>`. Really, the only purpose of this trait is to force users to write `use miniscript::TranslatePk` every time they want …
=> Remove `TranslatePk` trait and clean up `Translator` trait

src/primitives/relative_locktime.rs
I've just found out RelLockTime misses zero sequence check, which must be disallowed for miniscript.
=> fix: zero sequence check on relative time

src/util.rs
Miniscript witness item can be maximum 72 bytes(except length prefix), but it only throws error when it's >= 4294967296 bytes as only dependant on `PushBytesError` from bitcoin crate.  I've changed the logic to check the maximum length internally so that actual check can be done.
=> feat: actually check push data bytes

src/blanket_traits.rs, src/lib.rs, src/miniscript/mod.rs
This is a short PR in terms of LOC, but may be controversial. I think it is necessary though.
Currently we have `PartialEq` on our giant `Error` enum (though amusingly not `Eq`) so that we can use `assert_eq` in unit tests. We can get away with this because our error enum does not contain any `std::io::Error`s anywhere, which can't be compared, nor does it contain any boxed errors.
In the next couple of PRs I am going to clean up the `expression` module to make the parser non-recursive and the error types strongly typed and detailed. To do this, I want to store `<Pk as FromStr>::Err`s, which to avoid a `Pk` parameter on `Error`, will need to be boxed. When we box the type we need to declare upfront what traits the error types have, and these traits will become requirements of the …
=> Remove `PartialEq` impl from `Error`

src/miniscript/context.rs, src/miniscript/mod.rs
I’m not 100% sure if it’s intended, but the behavior of `check_global_consensus_validity`, which checks the script size limit first and then node could confuse the user-side.
For example, If `sh` or `wsh` descriptor uses `multi_a` with 999 public key(e.g. `descriptor::Wsh::from_str("wsh(multi_a(pk1...pk999)")`), it will throw an error on the size limit, not the fragment `multi_a`. It might be a bit more efficient in case of size overflow, but
1.  As miniscript functions as a language, syntax or grammar check should precedes stack limit. While the most of syntax are checked before `check_global_consensus_validity`, Syntax of which validity differ on context(e.g. `multi` and `multi_a`) are not.
2. It’s more helpful to debug for user if blocked by wrong syntax first.
3. It’s weird to check …
=> refactor: check the node syntax before size limit

src/policy/concrete.rs
Before this fix, the added test failed with: `Unexpected("Empty Miniscript compilation")`
=> Fix compilation of pk()-only policies into tr() descriptors

src/descriptor/key.rs
A small fix for a small oversight.
The test has to pattern match the inner `SinglePriv` because there's no other way to get derivation path (no `full_derivation_path(s)` method like `DescriptorPublicKey` has, which would be nice to have ^.^)
=> Fix decoding of WIF with BIP32 origin

src/miniscript/context.rs, src/miniscript/mod.rs
`BareCtx` consensus validity check returns `MaxWitnessScriptSizeExceeded` err when exceeding script size limit, which is wrong and confusing. Adding `MaxBareScriptSizeExceeded` and using it instead can clearly give a correct message on compile error.
=> feat: add MaxBareScriptSizeExceeded err for bare consensus check

src/descriptor/key.rs
Possible when all hardened derivation steps are shared among all paths (or if there are none). Errors otherwise.
=> Support conversion of multi-Xprivs into multi-Xpubs

src/miniscript/context.rs
Just fix the typo. Rename `MaxWitnessItemssExceeded` to `MaxWitnessItemsExceeded`.
=> fix: fix typo for MaxWitnessItemsExceeded

src/miniscript/context.rs, src/miniscript/mod.rs
`MaxWitnessScriptSizeExceeded` is used in the context of `SegwitV0` and `Tap`, where each of max witness script size differs. Moreover, even in the same context of `SegwitV0`, max witness script size differ whether it's standard or consensus rule. I just let `MaxWitnessScriptSizeExceeded` receive param `usize` to differentiate max witness script size upon context, which can fix the wrong err message of `"The Miniscript corresponding Script would be larger than MAX_STANDARD_P2WSH_SCRIPT_SIZE  bytes."` when `SegwitV0` consensus and `Tap` context
=> fix: differentiate max witness script size upon context

src/miniscript/context.rs, src/miniscript/mod.rs
919bc4b6c2ad37e94c446871de10a96c84b29f29
- use `ImpossibleSatisfaction` when op_count is None instead of `MaxOpCountExceeded`.
51a50ae3e81b02c4e8f4759df62186b53c5459ba
- unify error message for satisfaction-kind error and scriptPubKey-kind error so that these error can contain max(limit) with what it got(actual).
=> feature: improve context err

src/descriptor/checksum.rs, src/descriptor/mod.rs, src/descriptor/tr.rs, src/miniscript/iter.rs, src/miniscript/lex.rs, src/miniscript/mod.rs, src/miniscript/satisfy.rs, src/plan.rs, src/primitives/threshold.rs, src/psbt/mod.rs
When working with Taproot descriptors you typically need to do an annoying (and hard to discover) `match` statement to get the `Tr` out of the descriptor, and then call accessors on that to get the actual data out.
Add two new methods to `Descriptor` that directly access the internal key and the taptree. Document that the actual leaves can be obtained by calling `.iter` on the taptree.
Next, when a user is trying to sign a Taproot branch, they need to obtain a TapLeafHash. We have internal code which does this (which I have pulled into a helper function since there is some room to optimize it there..) but no exposed code, forcing the user to go digging through the rust-bitcoin docs to figure it out (including knowing the standard Taproot leaf version, which is an arcane detail of the sort …
=> descriptor: introduce several Taproot accessors

.github/workflows/cron-daily-fuzz.yml, fuzz/generate-files.sh
=> bump download- and upload-artifact to v4

src/miniscript/mod.rs
- `Miniscript::from_ast()` only executes `check_global_consensus_validity()` which does not include `check_global_policy_validity()`. Change to use `check_global_validity()` to check both consensus and policy validness.
- `wrap_into_miniscript()` executes `check_global_validity()` internally after `Miniscript::from_ast()`. As `Miniscript::from_ast()` now executes `check_global_validity()`,  it doesn't have to check duplicately.
I was originally thinking to change `check_global_validity()` inside `wrap_into_miniscript()` to `check_global_policy_validity()`(as consensus check is done by `from_ast()`). I think it's better to strengthen the validness check in `from_ast()`, and do nothing in `wrap_into_miniscript()`.
=> feat: check policy validity to prevent duplicate check

src/descriptor/bare.rs, src/descriptor/checksum.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/tr.rs, src/expression/error.rs, src/expression/mod.rs, src/lib.rs, src/miniscript/mod.rs, src/policy/concrete.rs, src/policy/semantic.rs
As a step toward rewriting the expression parser to be non-recursive, add a pre-parsing well-formedness check, which verifies that an expression is well-formed, uses only the correct character set, and that the checksum (if present) is valid.
Along the way, replace the error types returned from the `expression` module with a new more-precise one which can identify the location of parse errors (and identify what the error was in a more correct way). This improves our error reporting and drops many instances of the stringly-typed `BadDescriptor` error.
There is currently a bunch of special logic for Taproot descriptors which have the extra characters `{` and `}`. To the extent possible, this PR doesn't touch that logic. It will be addressed in a later PR.
The benchmarks show a slight …
=> refactor expression parsing and checksum checking

src/miniscript/lex.rs
I'm not sure whether it's intentional, but this pattern(match and then if) could make lexer little slower for `OP_CSV` and `OP_CLTV`(and `Error::InvalidOpcode`) as they aren't caught in match arms but `if` block like below(which causes additional check).
```rust
...
script::Instruction::Op(op) => {
if op == opcodes::all::OP_CSV {
ret.push(Token::CheckSequenceVerify);
} else if op == opcodes::all::OP_CLTV {
ret.push(Token::CheckLockTimeVerify);
} else {
return Err(Error::InvalidOpcode(op))
}
}
```
=> feat: remove inefficient if check on match lex

fuzz/README.md, src/descriptor/bare.rs, src/descriptor/checksum.rs, src/descriptor/mod.rs, src/descriptor/segwitv0.rs, src/descriptor/sh.rs, src/descriptor/sortedmulti.rs, src/descriptor/tr.rs, src/error.rs, src/expression/error.rs, src/expression/mod.rs, src/interpreter/inner.rs, src/interpreter/stack.rs, src/lib.rs, src/miniscript/decode.rs, src/miniscript/mod.rs, src/primitives/threshold.rs, src/psbt/mod.rs
This PR does several things but the only big commit is "unify Taproot and non-Taproot parsing" which replaces the ad-hoc logic in `Tr::from_str` to handle Taproot parsing with unified expression-parsing logic.
In addition to this, we also:
* rewrite the expression parser to be non-recursive, which is a reduction in LOC thanks to our prepatory work
* introduces an `error` module whose types will eventually replace the top-level `Error` enum
* relatedly, drops several error variants including the stringly-typed `BadDescriptor` (it does not get rid of `Unexpected` which is *also* a stringly-typed catch-all error, but we will..)
=> Rewrite expression parser to be non-recursive

bitcoind-tests/Cargo.toml
We just re-named and move the crate/repo from `rust-bitcoind-json` to `corepc`. Use the new name
For context see: https://github.com/rust-bitcoin/rust-bitcoind-json-rpc/pull/51
=> Use new corepc-node crate

CHANGELOG.md, Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, src/descriptor/tr.rs, src/miniscript/astelem.rs, src/primitives/relative_locktime.rs
We are incorrectly serializing and_n as "and_b", and incorrectly parsing `tr(<key>,)`.
In master the `and_b` thing is fixed by https://github.com/rust-bitcoin/rust-miniscript/pull/722 which rewrites the Display impl completely and the `tr(<key>,)` thing will be fixed as part of a coming series of PRs to clean up expression parsing.
Also includes #740 since it showed up in time.
=> [backport] Several small fixes for 12.x

src/miniscript/lex.rs
In [rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin/blob/aa25adfc64ea0d742ca202991140f280024aba1b/bitcoin/src/blockdata/script/push_bytes.rs#L312), `read_scriptint` checks `NonMinimalPush`, which makes an additional minimal check needless and `PushBytes` inefficient.
=> feat: optimize pushbytes by removing unreachable minimal check

.github/workflows/cron-daily-fuzz.yml, fuzz/generate-files.sh
Our `generate-files.sh` script got out of sync again.
I will try to add a check for this to my local CI.
Fixes #789
=> mechanical updates to fuzztests

.github/workflows/cron-daily-fuzz.yml, fuzz/Cargo.toml, fuzz/fuzz_targets/roundtrip_miniscript_script_tap.rs
This PR adds a new fuzz target to parse a miniscript from script hex for Tap. We currently have one target that does it for Segwitv0.
=> fuzz: add target for tapscript parsing from script

.github/workflows/cron-daily-fuzz.yml, fuzz/Cargo.toml, fuzz/fuzz_targets/miniscript_satisfy.rs, src/descriptor/checksum.rs, src/descriptor/mod.rs, src/miniscript/analyzable.rs, src/miniscript/satisfy.rs, src/psbt/mod.rs
There is a bunch of essentially-repeated "combine two satisfactions" code throughout satisfy.rs. It's hard to tell at a glance what order the concatenantions are in, even though this is essential, or whether the combination is actually done correctly. 
In particular, we routinely use the opposite order for Witness::combine and for ||'ing the has_sig, and we routinely assume that timelock conditions are None for dissatisfactions, which is true, but it's still a lot to keep in your head.
Also adds a fuzz test to sanity check our satisfactions (just checks for crashes; we don't check whether satisfaction "should" succeed since that's hard to tell in general.)
=> cleanup: refactor a bunch of concatenation-related code in `satisfy`

src/blanket_traits.rs, src/error.rs
=> Fix: make `StaticDebugAndDisplay` `Send` and `Sync`

Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, src/miniscript/iter.rs, src/miniscript/satisfy.rs
This backports the main commit in #798 so that the code in (released) 12.x is substantially the same as the code in (unreleased) 13.x. This makes it easier to write and maintain regression tests.
=> [backport] cleanup: refactor a bunch of concatenation-related code in satisfy

src/descriptor/key.rs, src/descriptor/mod.rs
This PR has a go at refactoring `DescriptorKeyParseError` into an enum, as suggested in the `FIXME` comment:
https://github.com/rust-bitcoin/rust-miniscript/blob/d0da327417cb177884c5d77edffa0891ba9b6969/src/descriptor/key.rs#L327-L330
I have separated the error variants by different inner parse error types and result types (e.g, public key, private key, etc) where I think it made sense to retain the inner error.
I left a variant that wraps a `&'static str` and its used for the various ad-hoc parsing errors instead of adding the boilerplate for variants only created once and without retained data.
The generic `parse_xkey_deriv` function now takes a parse function as its first parameter to allow specific key parsing errors:
https://github.com/chris-ricketts/rust-miniscript/blob/790b08fcf46f5 …
=> Refactor: make descriptors::key::DescriptorKeyParseError an enum

CHANGELOG.md
Add an entry to the CHANGELOG stating #798 was a silent fix for a crash bug which could be triggered by satisfying `thresh(k,subs)` fragments where `k == len(subs)`.
=> CVE-2025-43707 public disclosure

src/interpreter/inner.rs, src/lib.rs, src/miniscript/context.rs
This PR fixes several typos in comments and documentation:
- "iterpreter" -> "interpreter" in src/interpreter/inner.rs
- "transalation" -> "translation" in src/lib.rs  
- "reource" -> "resource" in src/miniscript/context.rs
These changes only affect comments and do not modify any functional code.
=> Fix typos: correct spelling of "interpreter", "translation" and "resource"

src/descriptor/key.rs, src/expression/error.rs, src/miniscript/context.rs
This PR fixes several typos across the codebase:
- src/descriptor/key.rs: Fix "occurence" -> "occurrence"
- src/expression/error.rs: Fix "occured" -> "occurred" 
- src/miniscript/context.rs: Fix "restrcted" -> "restricted" (in two places)
These are simple spelling corrections that don't affect functionality.
=> Fix typos: occurrence, occurred, restricted

src/descriptor/mod.rs, src/lib.rs
Thanks to Bruno Garcia and i-am-yuvi who independently found this crash and reported it to me.
Fixes #806
Needs backport.
=> fix crash in Descriptor::parse_desc found by fuzzer

Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, src/descriptor/mod.rs, src/lib.rs
Backports #809 and does another patch release.
=> Backport of #809: fix crash in `Descriptor::parse_desc`

src/descriptor/mod.rs, src/descriptor/tr/mod.rs, src/descriptor/tr/taptree.rs, src/lib.rs, src/policy/concrete.rs, src/policy/mod.rs
This PR completely rewrites the `TapTree` module to store a taptree as a flat list of leaves and heights. For a non-`ToPublicKey` key this is the only useful information that we ever extract from this, so storing a big recursive structure is wasteful. We also eliminate recursive code from everything `TapTree` related, including the implicit `Drop` impl.
In the next PR we'll introduce a new tree structure that contains control block information -- but `TapTree` can't be this structure because `TapTree` doesn't assume that its keys can be serialized.
Also breaks the `iter_scripts` iterator API in a couple small ways.
=> [Taproot API Project] flatten internal representation of `TapTree`

.github/workflows/fuzz.yml, Cargo.toml, fuzz/Cargo.toml, fuzz/fuzz-util.sh, src/descriptor/mod.rs, src/lib.rs
Backports #809 to 10.x. This is a direct rebase of #810 except that I added a commit with some lint fixes. (I had been avoiding this, but we've been having a lot of backports lately so I think I ought to just address it.)
After this I will do 11.x.
=> Backport #809 to 0.10.x

src/descriptor/key.rs, src/descriptor/mod.rs
closes https://github.com/rust-bitcoin/rust-miniscript/issues/817
I added the common cases of converting from `Descriptor<PublicKey>` and `Descriptor<XOnlyPublicKey>` to `Descriptor<DefinitePublicKey>`. Not sure if this is considered too specific but it feels like a use case that will be very common.
=> Add helpers to convert to DescriptorPublicKey and Descriptor<DefinitePublicKey> data structures

.github/workflows/fuzz.yml, Cargo.toml, fuzz/Cargo.toml, fuzz/fuzz-util.sh, src/descriptor/mod.rs, src/lib.rs
Backport of #809 to 11.x. Last backport for this PR.
=> Backport #809 to 11.x

src/plan.rs
"The size in bytes of the script sig that" is ambiguous and could refer to the actual scriptSig, exlcuding the varint prefix that indicates its size.
The code comment in witness_size is promoted to the docstring, as its helpful to anyone trying to compute the right size of a transaction.
=> plan: add some clarifying docs

src/descriptor/iter.rs, src/descriptor/mod.rs
Fixes #821.
Should backport to 12.x.
=> Add `Descriptor::iter_pk`

bitcoind-tests/tests/test_desc.rs, fuzz/fuzz_targets/regression_taptree.rs, src/descriptor/mod.rs, src/descriptor/tr/mod.rs, src/descriptor/tr/spend_info.rs, src/descriptor/tr/taptree.rs, src/psbt/mod.rs
In Miniscript, to compute control blocks, estimate satisfaction costs, or otherwise iterate through all the leaves of a Taptree, we use the `bitcoin::TaprootSpendInfo` structure to maintain a map of all leaves. This map is inappropriate for Miniscript (it may not be appropriate for *anyone* actually..) for a few reasons:
* It is a map from Tapleaves' encoding as Script to data about the Tapleaves; but in Miniscript the Script encoding isn't primary and isn't even available for non-`ToPublicKey` keys
* This map structure means that if duplicate leaves exist then only one of the dupes will be accessible.
* The map structure is also really inefficient; it stores the entire merkle path for each leaf even those these paths significantly overlap, leading to O(n log n) space instead of O(n).
* …
=> [Taproot API Project] replace `TaprootSpendInfo` with new miniscript-specific structure

src/descriptor/key.rs
This PR essentially just fixes a logic bug in `DefiniteDescriptorKey::new` but involves several commits that just rearrange error types.
I will backport the logic fix without the error refactoring, since for 12.x and earlier we didn't really have error types and were just returning `Error::Unexpected("arbitrary string")` style errors.
=> Properly forbid multipath keys in definite descriptor keys

Cargo.toml, src/descriptor/key.rs
Just the logic fix; the error refactoring doesn't apply.
=> backport #830 to rust-miniscript 10.x 

src/descriptor/tr/mod.rs
I *really* don't feel like I have enough context to be confident in this change, but at the same time this seems pretty obviously backwards to the best of my (currently lacking) knowledge.
=> Invert malleability test in `best_tap_spend`

fuzz/fuzz_targets/roundtrip_miniscript_script.rs, fuzz/fuzz_targets/roundtrip_miniscript_script_tap.rs, src/interpreter/inner.rs, src/lib.rs, src/miniscript/analyzable.rs, src/miniscript/decode.rs, src/miniscript/lex.rs, src/miniscript/mod.rs, src/psbt/finalizer.rs
The last commit, which renames `parse_with_ext` to `decode_with_ext`, I think we should backport with deprecation to 12.x. This is a pretty uncommonly used function and is unlikely to bother anybody, but the current name is inconsistent with our general use of "parse" for strings and "decode" for scripts.
=> various improvements/refactors of the decoder and its errors

src/plan.rs, src/util.rs
This is a simple fix for #771.
=> fix: include varints for Taproot script and control block sizes

src/descriptor/key_map.rs
Since #851 we return a `NotSupported` error when attempting to request an xpriv from an x-only key. I'm not sure if this is the correct semantics, but it was deliberately written, so we'll keep it. **However** the behavior was different for multipath xprivs. There we returned `None`, i.e. "key not found/mismatch" rather than an error.
This PR returns an error in both cases.
=> key_map.rs: propagate "invalid key" errors from multipath keys

Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, src/descriptor/key_map.rs, src/descriptor/mod.rs
backports #851 to release/12.x
It's an initial attempt to backport the implementation of GetKey for KeyMap introduced in #851.  
I noticed that the type `KeyMapWrapper` is already being used internally for parse_descriptor,   though, as it's not part of the public API, there's no conflict, but I'm fine with changing it to another name if needed.
```
- add `KeyMapWrapper` with `GetKey` trait for PSBT signing
- implement `GetKey` for `DescriptorSecretKey`
- add `From<KeyMap>` conversion
- export new `KeyMapWrapper` for downstream crate usage
```
=> feat(descriptor): backport `GetKey` impl from #851
